packages:
  - apps/*
  - napi/*
  - wasm/*
  - npm/*
  - tasks/e2e
  - tasks/transform_conformance
  - tasks/compat_data

catalog:
  "@emnapi/core": 1.11.1
  "@emnapi/runtime": 1.11.1
  "@arethetypeswrong/core": 0.18.4
  "@napi-rs/cli": 3.7.2
  "@napi-rs/wasm-runtime": 1.1.6
  "@types/node": 24.1.0
  cross-env: ^10.1.0
  degit: 3.4.7
  eslint: 10.5.0
  json-schema-to-typescript: ^15.0.4
  publint: 0.3.21
  rolldown: 1.1.4
  tsdown: 0.22.3
  vite-plus: 0.2.2
  vitest: 4.1.9

overrides:
  rolldown: "catalog:"

allowBuilds:
  "@vscode/vsce-sign@2.0.8": true
  esbuild@0.27.7: true
  esbuild@0.28.0: true
  "@nestjs/core@11.1.9": false

verifyDepsBeforeRun: install
minimumReleaseAgeExclude:
  - "@napi-rs/*"
  - "@oxc-parser/*"
  - "@oxc-project/*"
  - "@oxfmt/*"
  - "@oxlint-tsgolint/*"
  - "@oxlint/*"
  - "@rolldown/*"
  - "@tsdown/*"
  - "@vitejs/devtools"
  - "@vitest/*"
  - "@voidzero-dev/*"
  - oxc-parser
  - oxfmt
  - oxlint
  - oxlint-tsgolint
  - rolldown
  - tsdown
  - vite
  - vite-plus
  - vitest
