packages:
  - apps/*
  - napi/*
  - wasm/*
  - npm/*
  - tasks/e2e
  - tasks/transform_conformance
  - tasks/compat_data

catalog:
  "@emnapi/core": 1.10.0
  "@emnapi/runtime": 1.10.0
  "@arethetypeswrong/core": 0.18.2
  "@napi-rs/cli": 3.6.2
  "@napi-rs/wasm-runtime": 1.1.4
  "@types/node": 24.1.0
  cross-env: ^10.1.0
  eslint: 10.2.1
  json-schema-to-typescript: ^15.0.4
  publint: 0.3.18
  rolldown: 1.0.0
  tsdown: 0.22.0
  vitest: 4.1.5

allowBuilds:
  "@vscode/vsce-sign@2.0.8": true
  esbuild@0.27.7: true
  esbuild@0.28.0: true
  "@nestjs/core@11.1.9": false

verifyDepsBeforeRun: install
