/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Babel Parser Options
 *
 * <https://github.com/babel/babel/blob/main/packages/babel-parser/typings/babel-parser.d.ts>
 */
export interface ParserOptions {
  sourceType?: string
  sourceFilename?: string
}
export interface ParseResult {
  program: any
  errors: Array<string>
}
/**
 * # Panics
 * * File extension is invalid
 * * Serde JSON serialization
 */
export function parseSync(sourceText: string, options?: ParserOptions | undefined | null): ParseResult
/**
 * # Panics
 * * Tokio crashes
 */
export function parseAsync(sourceText: string, options?: ParserOptions | undefined | null): Promise<ParseResult>
