use oxc_allocator::Allocator;
use oxc_codegen::{Codegen, CodegenOptions};
use oxc_parser::Parser;
use oxc_semantic::SemanticBuilder;
use oxc_span::SourceType;
use oxc_transformer::{ESTarget, EnvOptions, TransformOptions, Transformer};
use std::path::Path;

use crate::{codegen, test};

/// Regression test: parameter property assignments must be inserted after all
/// conditional `super()` calls, not before them.
///
/// Before fix: `this.code = code` was inserted before `if (description) { _super(...) }`
/// causing `ReferenceError: Must call super constructor in derived class before
/// accessing 'this'`.
#[test]
fn class_properties_conditional_super_with_parameter_properties() {
    // Regression test for https://github.com/oxc-project/oxc/issues/20527
    let source = r#"class MyError extends Error {
  constructor(
    public code: string,
    public description: string,
  ) {
    if (description) {
      super(code + ': ' + description);
    } else {
      super(code);
    }
    this.name = 'MyError';
  }
}"#;

    let source_type = SourceType::ts();
    let allocator = Allocator::default();
    let ret = Parser::new(&allocator, source, source_type).parse();
    assert!(ret.errors.is_empty(), "parse errors: {:?}", ret.errors);

    let mut program = ret.program;
    let scoping = SemanticBuilder::new().build(&program).semantic.into_scoping();
    let ret =
        Transformer::new(&allocator, Path::new(""), &TransformOptions::from(ESTarget::ES2022))
            .build_with_scoping(scoping, &mut program);
    assert!(ret.errors.is_empty(), "transform errors: {:?}", ret.errors);

    let result = Codegen::new()
        .with_options(CodegenOptions { single_quote: true, ..CodegenOptions::default() })
        .build(&program)
        .code;

    // The `_super` function is only generated by the ES2022 class properties transform,
    // not by the TypeScript-only parameter property transform.
    // What matters is that parameter property initializers come AFTER the if-else block,
    // not before it.
    let if_pos = result.find("if (description)").unwrap();
    let this_code_pos = result.find("this.code = code").unwrap();

    // `this.code = code` must come AFTER the if-else block
    assert!(
        this_code_pos > if_pos,
        "parameter property initializer 'this.code = code' must come after the if-else block\n\
         if at: {if_pos}, this.code at: {this_code_pos}\n\
         output:\n{result}"
    );
}

#[test]
fn targets() {
    let cases = [
        ("() => {}"),
        ("a ** b"),
        ("async function foo() {}"),
        ("({ ...x })"),
        ("try {} catch {}"),
        ("a ?? b"),
        ("a ||= b"),
        "1n ** 2n",
    ];

    // Test no transformation for default targets.
    let options = TransformOptions {
        env: EnvOptions::from_browserslist_query("defaults").unwrap(),
        ..TransformOptions::default()
    };
    for case in cases {
        assert_eq!(Ok(codegen(case, SourceType::mjs())), test(case, &options));
    }

    // Test transformation for very low targets.
    let options = TransformOptions::from(ESTarget::ES2015);
    let options_node = TransformOptions {
        env: EnvOptions::from_browserslist_query("node 6").unwrap(),
        ..TransformOptions::default()
    };
    for case in cases {
        assert_eq!(test(case, &options), test(case, &options_node));
    }
}
