[package]
name = "oxc_diagnostics"
version = "0.146.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include = ["/src"]
keywords.workspace = true
license.workspace = true
publish = true
repository.workspace = true
rust-version.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
oxc_span = { workspace = true }

bytecount = { workspace = true }
cow-utils = { workspace = true }
itoa = { workspace = true }
memchr = { workspace = true }
owo-colors = { workspace = true }
percent-encoding = { workspace = true }
smallvec = { workspace = true }
textwrap = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }

[lib]
doctest = false
