[package]
name = "website_linter"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "website_linter"
doctest = false

[dependencies]
itertools = { workspace = true }
oxc_linter = { workspace = true, features = ["ruledocs"] }
oxlint = { workspace = true, features = ["ruledocs"] }
pico-args = { workspace = true }
project-root = { workspace = true }
schemars = { workspace = true }
website_common = { workspace = true }
usage-parser = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
