/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * NAPI entry point.
 *
 * JS side passes in:
 * 1. `args`: Command line arguments (process.argv.slice(2))
 * 2. `setup_config_cb`: Callback to setup Prettier config
 * 3. `format_embedded_cb`: Callback to format embedded code in templates
 * 4. `format_file_cb`: Callback to format files
 *
 * Returns `true` if formatting succeeded without errors, `false` otherwise.
 */
export declare function format(args: Array<string>, setupConfigCb: (configJSON: string, numThreads: number) => Promise<string[]>, formatEmbeddedCb: (tagName: string, code: string) => Promise<string>, formatFileCb: (parserName: string, fileName: string, code: string) => Promise<string>): Promise<boolean>
