/* auto-generated by NAPI-RS */
/* eslint-disable */
export type ExternalLinterCb =
  ((arg0: string, arg1: number) => string)

export type ExternalLinterLoadPluginCb =
  ((arg: string) => Promise<PluginLoadResult>)

export type PluginLoadResult =
  | { type: 'Success' }
  | { type: 'Failure', field0: string }
export declare function lint(buffers: Array<Uint8Array>, lintFile: ExternalLinterCb, loadPlugin: ExternalLinterLoadPluginCb): boolean
