/* auto-generated by NAPI-RS */
/* eslint-disable */
export type ExternalLinterCb =
  (() => void)

export type ExternalLinterLoadPluginCb =
  ((arg: string) => Promise<PluginLoadResult>)

export type PluginLoadResult =
  | { type: 'Success' }
  | { type: 'Failure', field0: string }
export declare function lint(loadPlugin: ExternalLinterLoadPluginCb, run: ExternalLinterCb): Promise<boolean>
