/* auto-generated by NAPI-RS */
/* eslint-disable */
export type JsLoadPluginCb =
  ((arg: string) => Promise<string>)

export type JsRunCb =
  (() => void)

export declare function lint(loadPlugin: JsLoadPluginCb, run: JsRunCb): Promise<boolean>
