/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TypeScriptBindingOptions {
  jsxPragma: string
  jsxPragmaFrag: string
  onlyRemoveTypeImports: boolean
  allowNamespaces: boolean
  allowDeclareFields: boolean
}
export interface ReactBindingOptions {
  runtime: 'classic' | 'automatic'
  development: boolean
  throwIfNamespace: boolean
  pure: boolean
  importSource?: string
  pragma?: string
  pragmaFrag?: string
  useBuiltIns?: boolean
  useSpread?: boolean
}
export interface ArrowFunctionsBindingOptions {
  spec: boolean
}
export interface Es2015BindingOptions {
  arrowFunction?: ArrowFunctionsBindingOptions
}
export interface TransformBindingOptions {
  typescript: TypeScriptBindingOptions
  react: ReactBindingOptions
  es2015: Es2015BindingOptions
}
export interface Sourcemap {
  file?: string
  mappings?: string
  sourceRoot?: string
  sources?: Array<string | undefined | null>
  sourcesContent?: Array<string | undefined | null>
  names?: Array<string>
}
export interface TransformResult {
  sourceText: string
  map?: Sourcemap
  errors: Array<string>
}
export function transform(filename: string, sourceText: string, options: TransformBindingOptions): TransformResult
export interface IsolatedDeclarationsResult {
  sourceText: string
  errors: Array<string>
}
/** TypeScript Isolated Declarations for Standalone DTS Emit */
export function isolatedDeclaration(filename: string, sourceText: string): IsolatedDeclarationsResult
