//! Node API binding which parses source text with [`oxc_parser`] and prints it with [`oxc_codegen`].
//!
//! This is the reference the `oxc-codegen` package's conformance tests are checked against.
//! For each fixture, the tests parse the source twice - once here in Rust, and once with `oxc-parser`
//! on the JS side - and require both printers to produce the same output and decoded source map positions.
//!
//! Both sides are given the same source text and the same `SourceType`, via [`oxc_napi::get_source_type`],
//! which is the same function `oxc-parser` itself uses to turn a filename and `lang` / `sourceType` options
//! into a `SourceType`. So the ASTs the two printers are handed are the same AST, and the only things
//! under test are printing and source map generation.

use std::{
    panic::{AssertUnwindSafe, catch_unwind},
    path::PathBuf,
};

use napi_derive::napi;

use oxc_allocator::Allocator;
use oxc_ast::ast::{
    ArrowFunctionExpression, ExportAllDeclaration, ExportFromDeclaration, Function,
    ImportDeclaration, WithClauseKeyword,
};
use oxc_ast_visit::{VisitMut, walk_mut};
use oxc_codegen::{Codegen, CodegenOptions, CommentOptions};
use oxc_napi::get_source_type;
use oxc_parser::{ParseOptions, Parser};
use oxc_sourcemap::napi::SourceMap;
use oxc_syntax::scope::ScopeFlags;

/// Options describing how a fixture should be parsed.
///
/// These are the same options the JS side passes to `oxc-parser`, so that both sides parse
/// the fixture identically.
#[napi(object)]
pub struct Options {
    /// `"js"`, `"jsx"`, `"ts"` or `"tsx"`. When absent, the language comes from the filename.
    pub lang: Option<String>,
    /// `"script"`, `"module"` or `"unambiguous"`. When absent, it comes from the language.
    pub source_type: Option<String>,
    /// Whether to keep the `ParenthesizedExpression` / `TSParenthesizedType` wrapper nodes.
    /// Default `false`.
    pub preserve_parens: Option<bool>,
}

/// Generated code and its source mappings.
#[napi(object)]
pub struct CodegenResult {
    /// Generated source text.
    pub code: String,
    /// Source map generated by `oxc_codegen`.
    pub map: SourceMap,
}

/// Parse `source_text` with `oxc_parser` and print the AST with `oxc_codegen`, including a source map.
///
/// Returns `null` if the source text could not be parsed without errors, which tells the caller
/// there is nothing to compare for this fixture.
///
/// Comments are not printed. `oxc-codegen` does not print comments, and the ESTree AST the JS side
/// works from carries no comment data anyway.
///
/// # Errors
///
/// Returns any panics as errors to avoid aborting the whole Node process.
#[napi]
#[expect(clippy::allow_attributes)]
#[allow(clippy::needless_pass_by_value)]
pub fn codegen(
    filename: String,
    source_text: String,
    options: Option<Options>,
) -> napi::Result<Option<CodegenResult>> {
    let options =
        options.unwrap_or(Options { lang: None, source_type: None, preserve_parens: None });

    // Oxc should never panic, but a panic in a Node addon aborts the process, which would throw
    // away the whole conformance run. Contain it, surfacing it as a JS error. `null` is reserved
    // for source text which could not be parsed cleanly and the JS side skips.
    catch_unwind(AssertUnwindSafe(|| {
        codegen_impl(
            &filename,
            &source_text,
            options.lang.as_deref(),
            options.source_type.as_deref(),
            options.preserve_parens.unwrap_or(false),
        )
    }))
    .map_err(|_| napi::Error::from_reason(format!("Oxc code generator panicked for {filename}")))
}

fn codegen_impl(
    filename: &str,
    source_text: &str,
    lang: Option<&str>,
    source_type_option: Option<&str>,
    preserve_parens: bool,
) -> Option<CodegenResult> {
    let source_type = get_source_type(filename, lang, source_type_option);

    let allocator = Allocator::default();
    let ret = Parser::new(&allocator, source_text, source_type)
        .with_options(ParseOptions {
            // Whatever the JS side was given.
            // Parse the same way, or the two printers would be given different ASTs,
            // and the comparison would be measuring the parse, not the print.
            preserve_parens,
            ..ParseOptions::default()
        })
        .parse();

    // Only print fixtures which parse cleanly. Oxc's parser recovers from errors, but a recovered
    // AST is not something the JS side can be expected to reproduce.
    if ret.panicked || !ret.diagnostics.is_empty() {
        return None;
    }

    let mut program = ret.program;
    Normalize { preserve_parens }.visit_program(&mut program);

    let codegen_options = CodegenOptions {
        comments: CommentOptions::disabled(),
        source_map_path: Some(PathBuf::from(filename)),
        ..CodegenOptions::default()
    };
    let ret = Codegen::new().with_options(codegen_options).build(&program);
    let map = ret.map.expect("source map generation was enabled").into();

    Some(CodegenResult { code: ret.code, map })
}

/// Erases the parts of Oxc's AST which its own ESTree representation cannot carry.
///
/// The JS side reaches the printer through `oxc-parser`'s ESTree AST. Where that AST holds less
/// than the Rust one, the JS printer cannot possibly reproduce what the Rust printer does with the
/// extra information, so the Rust AST is brought down to what ESTree can say before printing.
///
/// Each case below is a real difference in what the two representations can express,
/// not a workaround for a printer bug.
struct Normalize {
    /// `true` when the AST keeps its `ParenthesizedExpression` / `TSParenthesizedType` wrappers.
    preserve_parens: bool,
}

impl<'a> VisitMut<'a> for Normalize {
    /// ESTree has no way to record that a function expression was parenthesized,
    /// which is what Oxc's `pife` flag tracks (and prints parentheses for).
    ///
    /// With `preserve_parens`, it does not need one - the parentheses are in the AST
    /// as a `ParenthesizedExpression` of their own, which the JS side reads and prints.
    /// Oxc's own printer ignores that node and goes by `pife`, so the flag has to survive
    /// for the two to agree.
    fn visit_function(&mut self, func: &mut Function<'a>, flags: ScopeFlags) {
        if !self.preserve_parens {
            func.pife = false;
        }
        walk_mut::walk_function(self, func, flags);
    }

    /// As `visit_function`, for arrow functions.
    fn visit_arrow_function_expression(&mut self, arrow: &mut ArrowFunctionExpression<'a>) {
        if !self.preserve_parens {
            arrow.pife = false;
        }
        walk_mut::walk_arrow_function_expression(self, arrow);
    }

    /// ESTree cannot distinguish `import "m"` from `import {} from "m"` - `specifiers` is `[]` for both.
    /// It also cannot distinguish an attribute-less import from one with an empty `with {}` clause -
    /// `attributes` is `[]` for both.
    ///
    ///  It also does not record which keyword introduced the attributes, so `assert {...}` and `with {...}`
    /// are indistinguishable.
    fn visit_import_declaration(&mut self, decl: &mut ImportDeclaration<'a>) {
        if decl.specifiers.as_ref().is_some_and(|specifiers| specifiers.is_empty()) {
            decl.specifiers = None;
        }
        normalize_with_clause(&mut decl.with_clause);
        walk_mut::walk_import_declaration(self, decl);
    }

    /// As `visit_import_declaration`, for `export ... from "m"`.
    fn visit_export_from_declaration(&mut self, decl: &mut ExportFromDeclaration<'a>) {
        normalize_with_clause(&mut decl.with_clause);
        walk_mut::walk_export_from_declaration(self, decl);
    }

    /// As `visit_import_declaration`, for `export * from "m"`.
    fn visit_export_all_declaration(&mut self, decl: &mut ExportAllDeclaration<'a>) {
        normalize_with_clause(&mut decl.with_clause);
        walk_mut::walk_export_all_declaration(self, decl);
    }
}

/// Drop an empty `with` clause, and forget which keyword introduced a non-empty one.
fn normalize_with_clause(
    with_clause: &mut Option<oxc_allocator::Box<'_, oxc_ast::ast::WithClause<'_>>>,
) {
    if let Some(inner) = with_clause {
        inner.keyword = WithClauseKeyword::With;

        if let Some(first) = inner.with_entries.first() {
            // ESTree exposes the entries but not the `WithClause` wrapper or its `{` span.
            // Use the first location both representations can carry as the clause's mapping anchor.
            inner.span.start = first.span.start;
        } else {
            *with_clause = None;
        }
    }
}
