/// Auto generated by `tasks/a11y_data/src/lib.rs`.
use phf::phf_set;
#[derive(Copy, Clone, Eq, PartialEq, Debug)]
pub struct Attr {
    pub name: &'static str,
    pub value: Option<&'static str>,
}
#[derive(Copy, Clone, Eq, PartialEq, Debug)]
pub struct ElementSchema {
    pub name: &'static str,
    pub attributes: &'static [Attr],
}
pub static ABSTRACT_ROLES: phf::Set<&'static str> = phf_set! {
    "command", "composite", "input", "landmark", "range", "roletype", "section",
    "sectionhead", "select", "structure", "widget", "window",
};

pub static INTERACTIVE_ROLES: phf::Set<&'static str> = phf_set! {
    "button", "checkbox", "columnheader", "combobox", "doc-backlink", "doc-biblioref",
    "doc-glossref", "doc-noteref", "grid", "gridcell", "link", "listbox", "menu",
    "menubar", "menuitem", "menuitemcheckbox", "menuitemradio", "option", "radio",
    "radiogroup", "row", "rowheader", "scrollbar", "searchbox", "slider", "spinbutton",
    "switch", "tab", "tablist", "textbox", "tree", "treegrid", "treeitem", "toolbar",
};

pub static NONINTERACTIVE_ROLES: phf::Set<&'static str> = phf_set! {
    "alert", "alertdialog", "application", "article", "banner", "blockquote", "caption",
    "cell", "code", "complementary", "contentinfo", "definition", "deletion", "dialog",
    "directory", "doc-abstract", "doc-acknowledgments", "doc-afterword", "doc-appendix",
    "doc-biblioentry", "doc-bibliography", "doc-chapter", "doc-colophon",
    "doc-conclusion", "doc-cover", "doc-credit", "doc-credits", "doc-dedication",
    "doc-endnote", "doc-endnotes", "doc-epigraph", "doc-epilogue", "doc-errata",
    "doc-example", "doc-footnote", "doc-foreword", "doc-glossary", "doc-index",
    "doc-introduction", "doc-notice", "doc-pagebreak", "doc-pagefooter",
    "doc-pageheader", "doc-pagelist", "doc-part", "doc-preface", "doc-prologue",
    "doc-pullquote", "doc-qna", "doc-subtitle", "doc-tip", "doc-toc", "document",
    "emphasis", "feed", "figure", "form", "graphics-document", "graphics-object",
    "graphics-symbol", "group", "heading", "img", "insertion", "list", "listitem", "log",
    "main", "mark", "marquee", "math", "meter", "navigation", "none", "note",
    "paragraph", "presentation", "region", "rowgroup", "search", "separator", "status",
    "strong", "subscript", "superscript", "table", "tabpanel", "term", "time", "timer",
    "tooltip", "progressbar",
};

pub static INTERACTIVE_ELEMENT_SCHEMA: &[ElementSchema] = &[
    ElementSchema {
        name: "a",
        attributes: &[Attr { name: "href", value: None }],
    },
    ElementSchema {
        name: "area",
        attributes: &[Attr { name: "href", value: None }],
    },
    ElementSchema {
        name: "button",
        attributes: &[],
    },
    ElementSchema {
        name: "datalist",
        attributes: &[],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr {
                name: "type",
                value: Some("button"),
            },
        ],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr {
                name: "type",
                value: Some("image"),
            },
        ],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr {
                name: "type",
                value: Some("reset"),
            },
        ],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr {
                name: "type",
                value: Some("submit"),
            },
        ],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr {
                name: "type",
                value: Some("checkbox"),
            },
        ],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr { name: "list", value: None },
            Attr {
                name: "type",
                value: Some("email"),
            },
        ],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr { name: "list", value: None },
            Attr {
                name: "type",
                value: Some("search"),
            },
        ],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr { name: "list", value: None },
            Attr {
                name: "type",
                value: Some("tel"),
            },
        ],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr { name: "list", value: None },
            Attr {
                name: "type",
                value: Some("text"),
            },
        ],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr { name: "list", value: None },
            Attr {
                name: "type",
                value: Some("url"),
            },
        ],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr {
                name: "type",
                value: Some("radio"),
            },
        ],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr { name: "list", value: None },
            Attr {
                name: "type",
                value: Some("search"),
            },
        ],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr {
                name: "type",
                value: Some("range"),
            },
        ],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr {
                name: "type",
                value: Some("number"),
            },
        ],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr { name: "type", value: None },
            Attr { name: "list", value: None },
        ],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr { name: "list", value: None },
            Attr {
                name: "type",
                value: Some("email"),
            },
        ],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr { name: "list", value: None },
            Attr {
                name: "type",
                value: Some("tel"),
            },
        ],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr { name: "list", value: None },
            Attr {
                name: "type",
                value: Some("text"),
            },
        ],
    },
    ElementSchema {
        name: "input",
        attributes: &[
            Attr { name: "list", value: None },
            Attr {
                name: "type",
                value: Some("url"),
            },
        ],
    },
    ElementSchema {
        name: "option",
        attributes: &[],
    },
    ElementSchema {
        name: "select",
        attributes: &[
            Attr {
                name: "multiple",
                value: None,
            },
            Attr { name: "size", value: None },
        ],
    },
    ElementSchema {
        name: "select",
        attributes: &[Attr { name: "size", value: None }],
    },
    ElementSchema {
        name: "select",
        attributes: &[
            Attr {
                name: "multiple",
                value: None,
            },
        ],
    },
    ElementSchema {
        name: "td",
        attributes: &[],
    },
    ElementSchema {
        name: "textarea",
        attributes: &[],
    },
    ElementSchema {
        name: "th",
        attributes: &[],
    },
    ElementSchema {
        name: "th",
        attributes: &[
            Attr {
                name: "scope",
                value: Some("col"),
            },
        ],
    },
    ElementSchema {
        name: "th",
        attributes: &[
            Attr {
                name: "scope",
                value: Some("colgroup"),
            },
        ],
    },
    ElementSchema {
        name: "th",
        attributes: &[
            Attr {
                name: "scope",
                value: Some("row"),
            },
        ],
    },
    ElementSchema {
        name: "th",
        attributes: &[
            Attr {
                name: "scope",
                value: Some("rowgroup"),
            },
        ],
    },
    ElementSchema {
        name: "tr",
        attributes: &[],
    },
];

pub static NONINTERACTIVE_ELEMENT_SCHEMA: &[ElementSchema] = &[
    ElementSchema {
        name: "address",
        attributes: &[],
    },
    ElementSchema {
        name: "article",
        attributes: &[],
    },
    ElementSchema {
        name: "aside",
        attributes: &[],
    },
    ElementSchema {
        name: "aside",
        attributes: &[
            Attr {
                name: "aria-label",
                value: None,
            },
        ],
    },
    ElementSchema {
        name: "aside",
        attributes: &[
            Attr {
                name: "aria-labelledby",
                value: None,
            },
        ],
    },
    ElementSchema {
        name: "blockquote",
        attributes: &[],
    },
    ElementSchema {
        name: "caption",
        attributes: &[],
    },
    ElementSchema {
        name: "code",
        attributes: &[],
    },
    ElementSchema {
        name: "dd",
        attributes: &[],
    },
    ElementSchema {
        name: "del",
        attributes: &[],
    },
    ElementSchema {
        name: "details",
        attributes: &[],
    },
    ElementSchema {
        name: "dfn",
        attributes: &[],
    },
    ElementSchema {
        name: "dialog",
        attributes: &[],
    },
    ElementSchema {
        name: "dt",
        attributes: &[],
    },
    ElementSchema {
        name: "em",
        attributes: &[],
    },
    ElementSchema {
        name: "fieldset",
        attributes: &[],
    },
    ElementSchema {
        name: "figure",
        attributes: &[],
    },
    ElementSchema {
        name: "footer",
        attributes: &[],
    },
    ElementSchema {
        name: "form",
        attributes: &[
            Attr {
                name: "aria-label",
                value: None,
            },
        ],
    },
    ElementSchema {
        name: "form",
        attributes: &[
            Attr {
                name: "aria-labelledby",
                value: None,
            },
        ],
    },
    ElementSchema {
        name: "form",
        attributes: &[Attr { name: "name", value: None }],
    },
    ElementSchema {
        name: "h1",
        attributes: &[],
    },
    ElementSchema {
        name: "h2",
        attributes: &[],
    },
    ElementSchema {
        name: "h3",
        attributes: &[],
    },
    ElementSchema {
        name: "h4",
        attributes: &[],
    },
    ElementSchema {
        name: "h5",
        attributes: &[],
    },
    ElementSchema {
        name: "h6",
        attributes: &[],
    },
    ElementSchema {
        name: "header",
        attributes: &[],
    },
    ElementSchema {
        name: "hr",
        attributes: &[],
    },
    ElementSchema {
        name: "html",
        attributes: &[],
    },
    ElementSchema {
        name: "img",
        attributes: &[Attr { name: "alt", value: None }],
    },
    ElementSchema {
        name: "img",
        attributes: &[Attr { name: "alt", value: None }],
    },
    ElementSchema {
        name: "img",
        attributes: &[
            Attr {
                name: "alt",
                value: Some(""),
            },
        ],
    },
    ElementSchema {
        name: "ins",
        attributes: &[],
    },
    ElementSchema {
        name: "li",
        attributes: &[],
    },
    ElementSchema {
        name: "main",
        attributes: &[],
    },
    ElementSchema {
        name: "mark",
        attributes: &[],
    },
    ElementSchema {
        name: "math",
        attributes: &[],
    },
    ElementSchema {
        name: "menu",
        attributes: &[],
    },
    ElementSchema {
        name: "meter",
        attributes: &[],
    },
    ElementSchema {
        name: "nav",
        attributes: &[],
    },
    ElementSchema {
        name: "ol",
        attributes: &[],
    },
    ElementSchema {
        name: "optgroup",
        attributes: &[],
    },
    ElementSchema {
        name: "output",
        attributes: &[],
    },
    ElementSchema {
        name: "p",
        attributes: &[],
    },
    ElementSchema {
        name: "progress",
        attributes: &[],
    },
    ElementSchema {
        name: "section",
        attributes: &[
            Attr {
                name: "aria-label",
                value: None,
            },
        ],
    },
    ElementSchema {
        name: "section",
        attributes: &[
            Attr {
                name: "aria-labelledby",
                value: None,
            },
        ],
    },
    ElementSchema {
        name: "strong",
        attributes: &[],
    },
    ElementSchema {
        name: "sub",
        attributes: &[],
    },
    ElementSchema {
        name: "sup",
        attributes: &[],
    },
    ElementSchema {
        name: "table",
        attributes: &[],
    },
    ElementSchema {
        name: "tbody",
        attributes: &[],
    },
    ElementSchema {
        name: "td",
        attributes: &[],
    },
    ElementSchema {
        name: "tfoot",
        attributes: &[],
    },
    ElementSchema {
        name: "thead",
        attributes: &[],
    },
    ElementSchema {
        name: "time",
        attributes: &[],
    },
    ElementSchema {
        name: "ul",
        attributes: &[],
    },
];

pub static NONINTERACTIVE_AXOBJECT_ELEMENT_SCHEMA: &[ElementSchema] = &[
    ElementSchema {
        name: "abbr",
        attributes: &[],
    },
    ElementSchema {
        name: "article",
        attributes: &[],
    },
    ElementSchema {
        name: "blockquote",
        attributes: &[],
    },
    ElementSchema {
        name: "br",
        attributes: &[],
    },
    ElementSchema {
        name: "caption",
        attributes: &[],
    },
    ElementSchema {
        name: "dd",
        attributes: &[],
    },
    ElementSchema {
        name: "details",
        attributes: &[],
    },
    ElementSchema {
        name: "dfn",
        attributes: &[],
    },
    ElementSchema {
        name: "dialog",
        attributes: &[],
    },
    ElementSchema {
        name: "dir",
        attributes: &[],
    },
    ElementSchema {
        name: "dl",
        attributes: &[],
    },
    ElementSchema {
        name: "dt",
        attributes: &[],
    },
    ElementSchema {
        name: "figcaption",
        attributes: &[],
    },
    ElementSchema {
        name: "figure",
        attributes: &[],
    },
    ElementSchema {
        name: "footer",
        attributes: &[],
    },
    ElementSchema {
        name: "form",
        attributes: &[],
    },
    ElementSchema {
        name: "h1",
        attributes: &[],
    },
    ElementSchema {
        name: "h2",
        attributes: &[],
    },
    ElementSchema {
        name: "h3",
        attributes: &[],
    },
    ElementSchema {
        name: "h4",
        attributes: &[],
    },
    ElementSchema {
        name: "h5",
        attributes: &[],
    },
    ElementSchema {
        name: "h6",
        attributes: &[],
    },
    ElementSchema {
        name: "iframe",
        attributes: &[],
    },
    ElementSchema {
        name: "img",
        attributes: &[
            Attr {
                name: "usemap",
                value: None,
            },
        ],
    },
    ElementSchema {
        name: "img",
        attributes: &[],
    },
    ElementSchema {
        name: "label",
        attributes: &[],
    },
    ElementSchema {
        name: "legend",
        attributes: &[],
    },
    ElementSchema {
        name: "li",
        attributes: &[],
    },
    ElementSchema {
        name: "main",
        attributes: &[],
    },
    ElementSchema {
        name: "mark",
        attributes: &[],
    },
    ElementSchema {
        name: "marquee",
        attributes: &[],
    },
    ElementSchema {
        name: "menu",
        attributes: &[],
    },
    ElementSchema {
        name: "meter",
        attributes: &[],
    },
    ElementSchema {
        name: "nav",
        attributes: &[],
    },
    ElementSchema {
        name: "ol",
        attributes: &[],
    },
    ElementSchema {
        name: "p",
        attributes: &[],
    },
    ElementSchema {
        name: "pre",
        attributes: &[],
    },
    ElementSchema {
        name: "progress",
        attributes: &[],
    },
    ElementSchema {
        name: "ruby",
        attributes: &[],
    },
    ElementSchema {
        name: "table",
        attributes: &[],
    },
    ElementSchema {
        name: "time",
        attributes: &[],
    },
    ElementSchema {
        name: "tr",
        attributes: &[],
    },
    ElementSchema {
        name: "ul",
        attributes: &[],
    },
];

