/* auto-generated by NAPI-RS */
/* eslint-disable */
export type JsLoadPluginCb =
  ((arg: string) => Promise<string>)

export type JsRunCb =
  ((arg0: string, arg1: number, arg2: Uint8Array | undefined | null, arg3: Array<number>) => string)

export declare function lint(loadPlugin: JsLoadPluginCb, run: JsRunCb): Promise<boolean>
