import { Worker } from "node:worker_threads";
import { lint, notifyWorkerDied } from "./bindings.js";
import { debugAssertIsNonNull, debugAssertIsNotUndefined } from "./utils/asserts.ts";

// Lazy-loaded JS plugin-related functions.
// The type annotations below use `typeof import("./plugins/index.ts").<fn>` so that the lazy-loaded variables
// always have the exact same function signatures as the implementations exported from the plugins module.
let loadPlugin: typeof import("./plugins/index.ts").loadPlugin | null = null;
let setupRuleConfigs: typeof import("./plugins/index.ts").setupRuleConfigs | null = null;
let lintFile: typeof import("./plugins/index.ts").lintFile | null = null;
let forgetBuffer: typeof import("./plugins/index.ts").forgetBuffer | null = null;
let createWorkspace: typeof import("./workspace/index.ts").createWorkspace | null = null;
let destroyWorkspace: typeof import("./workspace/index.ts").destroyWorkspace | null = null;
// Lazy-loaded JS/TS config loader (experimental)
let resolvedConfigLoader: import("./js_config.ts").ConfigLoader | null = null;

/**
 * Load a plugin.
 *
 * Lazy-loads plugins code on first call, so that overhead is skipped if user doesn't use JS plugins.
 *
 * @param path - Absolute path of plugin file
 * @param pluginName - Plugin name (either alias or package name)
 * @param pluginNameIsAlias - `true` if plugin name is an alias (takes priority over name that plugin defines itself)
 * @param workspaceUri - Workspace URI (`null` in CLI mode, `string` in LSP mode)
 * @returns Plugin details or error serialized to JSON string
 */
function loadPluginWrapper(
  path: string,
  pluginName: string | null | undefined,
  pluginNameIsAlias: boolean,
  workspaceUri: string | null | undefined,
): Promise<string> {
  // Type generated by NAPI-RS for `lint` is inaccurate.
  // `Option::None` on Rust side becomes `null` on JS side, not `undefined`.
  debugAssertIsNotUndefined(pluginName, "`pluginName` should not be `undefined`");
  debugAssertIsNotUndefined(workspaceUri, "`workspaceUri` should not be `undefined`");

  if (loadPlugin === null) {
    // Use promises here instead of making `loadPluginWrapper` an async function,
    // to avoid a micro-tick and extra wrapper `Promise` in all later calls to `loadPluginWrapper`
    return import("./plugins/index.ts").then((mod) => {
      ({ loadPlugin, lintFile, setupRuleConfigs, forgetBuffer } = mod);
      return loadPlugin(path, pluginName, pluginNameIsAlias, workspaceUri);
    });
  }
  return loadPlugin(path, pluginName, pluginNameIsAlias, workspaceUri);
}

/**
 * Bootstrap configuration options.
 *
 * Delegates to `setupRuleConfigs`, which was lazy-loaded by `loadPluginWrapper`.
 *
 * @param optionsJSON - Array of all rule options across all configurations, serialized as JSON
 * @returns `null` if success, or error message string
 */
function setupRuleConfigsWrapper(optionsJSON: string): string | null {
  debugAssertIsNonNull(setupRuleConfigs);
  return setupRuleConfigs(optionsJSON);
}

/**
 * Lint a file.
 *
 * Delegates to `lintFile`, which was lazy-loaded by `loadPluginWrapper`.
 *
 * @param filePath - Absolute path of file being linted
 * @param bufferId - ID of buffer containing file data
 * @param buffer - Buffer containing file data, or `null` if buffer with this ID was previously sent to JS
 * @param ruleIds - IDs of rules to run on this file
 * @param optionsIds - IDs of options to use for rules on this file, in same order as `ruleIds`
 * @param settingsJSON - Settings for file, as JSON
 * @param globalsJSON - Globals for file, as JSON
 * @param workspaceUri - Workspace URI (`null` in CLI mode, `string` in LSP mode)
 * @returns Diagnostics or error serialized to JSON string
 */
function lintFileWrapper(
  filePath: string,
  bufferId: number,
  buffer: Uint8Array | null | undefined,
  ruleIds: number[],
  optionsIds: number[],
  settingsJSON: string,
  globalsJSON: string,
  workspaceUri: string | null | undefined,
): string | null {
  // Type generated by NAPI-RS for `lint` is inaccurate.
  // `Option::None` on Rust side becomes `null` on JS side, not `undefined`.
  debugAssertIsNotUndefined(buffer, "`buffer` should not be `undefined`");
  debugAssertIsNotUndefined(workspaceUri, "`workspaceUri` should not be `undefined`");

  // `lintFileWrapper` is never called without `loadPluginWrapper` being called first,
  // so `lintFile` must be defined here
  debugAssertIsNonNull(lintFile);
  return lintFile(
    filePath,
    bufferId,
    buffer,
    ruleIds,
    optionsIds,
    settingsJSON,
    globalsJSON,
    workspaceUri,
  );
}

/**
 * Drop the cached buffer with this ID.
 *
 * Delegates to `forgetBuffer`, which was lazy-loaded by `loadPluginWrapper`. Rust only asks to
 * forget buffers it previously sent to JS, so the plugins module is always loaded by then.
 *
 * @param bufferId - ID of buffer to forget
 */
function forgetBufferWrapper(bufferId: number): undefined {
  debugAssertIsNonNull(forgetBuffer);
  forgetBuffer(bufferId);
}

/**
 * Create a new workspace.
 *
 * Lazy-loads workspace code on first call, so that overhead is skipped if user doesn't use JS plugins.
 *
 * @param workspace - Workspace URI
 * @returns Promise which resolves when workspace is created
 */
function createWorkspaceWrapper(workspace: string): Promise<undefined> {
  if (createWorkspace === null) {
    // Use promises here instead of making `createWorkspaceWrapper` an async function,
    // to avoid a micro-tick and extra wrapper `Promise` in all later calls to `createWorkspaceWrapper`
    return import("./workspace/index.ts").then((mod) => {
      ({ createWorkspace, destroyWorkspace } = mod);
      return createWorkspace(workspace);
    });
  }
  return Promise.resolve(createWorkspace(workspace));
}

/**
 * Destroy a workspace.
 *
 * Delegates to `destroyWorkspace`, which was lazy-loaded by `createWorkspaceWrapper`.
 *
 * @param workspace - Workspace URI
 * @returns `undefined`
 */
function destroyWorkspaceWrapper(workspace: string): undefined {
  // `destroyWorkspaceWrapper` is never called without `createWorkspaceWrapper` being called first,
  // so `destroyWorkspace` must be defined here
  debugAssertIsNonNull(destroyWorkspace);
  destroyWorkspace(workspace);
}
/**
 * Load JavaScript/TypeScript config files (experimental).
 *
 * Lazy-loads the js_config module on first call.
 * Uses native Node.js TypeScript support to import config files.
 *
 * @param paths - Array of absolute paths to JavaScript/TypeScript config files
 * @returns JSON-stringified result with all configs or error
 */
function loadJsConfigsWrapper(paths: string[]): Promise<string> {
  if (resolvedConfigLoader === null) {
    return import("./js_config.ts").then(({ loadJsConfigs, loadVitePlusConfigs }) => {
      resolvedConfigLoader = process.env.VP_VERSION ? loadVitePlusConfigs : loadJsConfigs;
      return resolvedConfigLoader(paths);
    });
  }
  return resolvedConfigLoader(paths);
}

const WORKER_URL = new URL("./worker.js", import.meta.url);

// How long to wait for all workers to report `ready` before giving up.
const WORKER_BOOT_TIMEOUT_MS = 5000;

// Workers started by `startJsWorkersWrapper`. Terminated once `lint` returns.
let workers: Worker[] = [];

// `true` once `terminateJsWorkers` has run, so the `exit`/`error` that follows an intentional
// `terminate()` is not reported to Rust as a worker death.
let shuttingDownJsWorkers = false;

// Test-only SharedArrayBuffer so fixture plugins can `Atomics.add` in `createOnce`.
// Created when `OXLINT_TEST_CREATE_ONCE_COUNTER` is set; read after `lint` returns.
let testCreateOnceCounter: SharedArrayBuffer | null = null;

// Debounce timer for `occupied_buffers=` stderr lines (test-only).
let occupiedReportTimer: ReturnType<typeof setTimeout> | undefined;

type WorkerMessage = { type: string; count?: number };

/**
 * Ask every live worker for `occupiedBufferCount()` and sum the replies.
 *
 * Used by the `OXLINT_TEST_OCCUPIED_BUFFERS` hook. Returns `null` if any isolate does not
 * answer in time — a timeout must not be reported as `0` (that would pass `occupied ≤ K`).
 */
async function queryOccupiedBufferCount(): Promise<number | null> {
  if (workers.length === 0) return 0;
  // Do not use `Promise.all` here: the CLI bundle extracts it to a free function and
  // `Promise.all` then throws (`this` is not `Promise`).
  const pending = workers.map((worker) => queryOneOccupiedCount(worker));
  let sum = 0;
  for (const reply of pending) {
    // oxlint-disable-next-line no-await-in-loop -- `Promise.all` is extracted by the CLI bundle and throws
    const count = await reply;
    if (count === null) return null;
    sum += count;
  }
  return sum;
}

function queryOneOccupiedCount(worker: Worker): Promise<number | null> {
  return new Promise((resolve) => {
    const timer = setTimeout(() => {
      worker.off("message", onMessage);
      resolve(null);
    }, 2000);
    const onMessage = (message: WorkerMessage) => {
      if (message.type !== "occupiedBufferCount") return;
      clearTimeout(timer);
      worker.off("message", onMessage);
      resolve(message.count ?? 0);
    };
    worker.on("message", onMessage);
    worker.postMessage({ type: "occupiedBufferCount" });
  });
}

/**
 * After a burst of `forgetBuffer` calls, print the sum of occupied JS buffers across workers.
 */
function scheduleOccupiedBufferReport(): void {
  if (!process.env.OXLINT_TEST_OCCUPIED_BUFFERS) return;
  clearTimeout(occupiedReportTimer);
  occupiedReportTimer = setTimeout(() => {
    void queryOccupiedBufferCount().then((count) => {
      if (count === null) {
        process.stderr.write("occupied_query_failed=timeout\n");
        return;
      }
      process.stderr.write(`occupied_buffers=${count}\n`);
    });
  }, 100);
}

/**
 * Report that a worker died after it had become ready.
 *
 * Rust threads block waiting for `lintFile` results from a specific worker, so a worker that dies
 * with calls in flight would hang every file whose buffer routes to it. Telling Rust lets those
 * waits fail instead.
 *
 * @param id - ID of the worker that died
 * @param reason - Why the worker died, for the message written to stderr
 */
function reportJsWorkerDeath(id: number, reason: string): void {
  if (shuttingDownJsWorkers) return;
  process.stderr.write(`oxlint: JS plugin worker ${id} died (${reason})\n`);
  notifyWorkerDied(id);
}

/**
 * Start `k` JS plugin worker isolates, and wait until all of them have registered their callbacks.
 *
 * Each worker calls `registerWorker` on the Rust side and then posts `ready`, so once every worker
 * is ready, Rust can route lint requests to any of them. Rust decides `k` and calls this at most
 * once per process, and never with `k <= 1` (a single isolate runs plugins on this thread instead).
 *
 * @param k - Number of workers to start
 * @returns Promise which resolves when all workers are ready
 * @throws If any worker fails to start, exits early, or does not become ready in time
 */
function startJsWorkersWrapper(k: number): Promise<undefined> {
  return new Promise((resolve, reject) => {
    let readyCount = 0;
    let settled = false;

    const settle = (err?: Error) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      if (err) {
        terminateJsWorkers();
        reject(err);
      } else {
        resolve(undefined);
      }
    };

    const timeout = setTimeout(() => {
      settle(
        new Error(
          `Timed out after ${WORKER_BOOT_TIMEOUT_MS}ms waiting for ${k} workers ` +
            `to start (${readyCount} ready)`,
        ),
      );
    }, WORKER_BOOT_TIMEOUT_MS);
    // Don't hold the event loop open just for the timeout
    timeout.unref?.();

    if (process.env.OXLINT_TEST_CREATE_ONCE_COUNTER) {
      testCreateOnceCounter = new SharedArrayBuffer(Int32Array.BYTES_PER_ELEMENT);
    }
    if (process.env.OXLINT_TEST_CREATE_ONCE_COUNTER || process.env.OXLINT_TEST_OCCUPIED_BUFFERS) {
      process.stderr.write(`js_workers=${k}\n`);
    }

    for (let id = 0; id < k; id++) {
      // `resourceLimits` caps each worker's JS heap. It does not cap the 2 GiB raw-transfer views,
      // which are external memory.
      const worker = new Worker(WORKER_URL, {
        workerData: testCreateOnceCounter
          ? { id, createOnceCounter: testCreateOnceCounter }
          : { id },
        resourceLimits: { maxOldGenerationSizeMb: 256 },
        stdout: true,
        stderr: false,
        stdin: false,
      });
      workers.push(worker);

      // Anything a plugin writes to stdout would corrupt the LSP protocol, and in CLI mode it would
      // interleave with diagnostics, so redirect it to stderr.
      worker.stdout.on("data", (buf) => process.stderr.write(buf));

      worker.on("message", (message: WorkerMessage) => {
        if (message.type === "ready" && ++readyCount === k) settle();
        if (message.type === "forgot") scheduleOccupiedBufferReport();
      });
      // Before all workers are ready, either event fails startup. Afterwards, startup is already
      // resolved, so the only thing left to do is release the Rust threads waiting on this worker.
      worker.on("error", (err) => {
        if (settled) reportJsWorkerDeath(id, err.message || String(err));
        else settle(err);
      });
      worker.on("exit", (code) => {
        if (!settled) {
          settle(
            new Error(`JS plugin worker ${id} exited with code ${code} before becoming ready`),
          );
        } else if (code !== 0) {
          reportJsWorkerDeath(id, `exit code ${code}`);
        }
        // A zero exit code after `ready` is the worker's event loop draining once Rust has released
        // its callbacks, which is how every run ends. Not a death, and nothing is waiting on it.
      });
    }
  });
}

/**
 * Terminate all JS plugin worker isolates.
 *
 * Workers hold raw-transfer buffers alive, and their `exit` listeners would otherwise keep the
 * process from exiting cleanly, so drop both here. The `exit` this triggers is intentional, so it
 * must not be reported to Rust as a worker death.
 */
function terminateJsWorkers(): void {
  shuttingDownJsWorkers = true;
  clearTimeout(occupiedReportTimer);
  const running = workers;
  workers = [];
  for (const worker of running) {
    worker.removeAllListeners("exit");
    worker.removeAllListeners("error");
    void worker.terminate();
  }
}

// Get command line arguments, skipping first 2 (node binary and script path)
const args = process.argv.slice(2);

// Node.js sets non-TTY `stdio` to non-blocking mode, which causes "Resource temporarily unavailable" errors
// in language server when passing a lot of data via stdin/stdout.
// https://github.com/oxc-project/oxc/issues/19265
// See also issue related to this workaround in `oxfmt` CLI:
// https://github.com/oxc-project/oxc/issues/17939
//
// As a workaround, if used with pipe, set blocking mode before calling NAPI bindings.
// See: https://github.com/napi-rs/napi-rs/issues/1630
if (!process.stdout.isTTY) {
  // @ts-expect-error: `_handle` is an internal API
  process.stdin._handle?.setBlocking?.(true);
  // @ts-expect-error: `_handle` is an internal API
  process.stdout._handle?.setBlocking?.(true);
}

// LSP uses stdout for communication, so write logs to stderr to avoid breaking the protocol.
// Since LSP is handled on the Rust side, we have to check the flag here. (`lint()` starts the server and waits)
// Also, for Oxlint, this actually affects:
// - loading JS/TS config files
// - Execution of JS plugins
if (args.includes("--lsp")) process.stdout.write = process.stderr.write.bind(process.stderr);

// Call Rust, passing callbacks and CLI arguments
let success: boolean;
try {
  success = await lint(
    args,
    loadPluginWrapper,
    setupRuleConfigsWrapper,
    lintFileWrapper,
    forgetBufferWrapper,
    createWorkspaceWrapper,
    destroyWorkspaceWrapper,
    loadJsConfigsWrapper,
    startJsWorkersWrapper,
  );
} finally {
  if (testCreateOnceCounter) {
    const count = Atomics.load(new Int32Array(testCreateOnceCounter), 0);
    process.stderr.write(`create_once_count=${count}\n`);
  }
  terminateJsWorkers();
}

// Note: It's recommended to set `process.exitCode` instead of calling `process.exit()`.
// `process.exit()` kills the process immediately and `stdout` may not be flushed before process dies.
// https://nodejs.org/api/process.html#processexitcode
if (!success) process.exitCode = 1;
