checker.ts:
  file size: 2922154 # 2.92 MB
  sys allocs: 46
  sys reallocs: 0
  sys deallocs: 46
  sys alloc bytes: 3866958 # 3.87 MB
  sys peak growth: 3858362 # 3.86 MB
  arena allocs: 0
  arena reallocs: 0
  arena size: 11835184 # 11.84 MB

App.tsx:
  file size: 415342 # 415.34 kB
  sys allocs: 7
  sys reallocs: 0
  sys deallocs: 7
  sys alloc bytes: 360848 # 360.85 kB
  sys peak growth: 360848 # 360.85 kB
  arena allocs: 0
  arena reallocs: 0
  arena size: 2095184 # 2.10 MB

RadixUIAdoptionSection.jsx:
  file size: 2520 # 2.52 kB
  sys allocs: 7
  sys reallocs: 0
  sys deallocs: 7
  sys alloc bytes: 2748 # 2.75 kB
  sys peak growth: 2748 # 2.75 kB
  arena allocs: 0
  arena reallocs: 0
  arena size: 18960 # 18.96 kB

pdf.mjs:
  file size: 567296 # 567.30 kB
  sys allocs: 12
  sys reallocs: 0
  sys deallocs: 12
  sys alloc bytes: 833710 # 833.71 kB
  sys peak growth: 832762 # 832.76 kB
  arena allocs: 0
  arena reallocs: 0
  arena size: 4153800 # 4.15 MB

antd.js:
  file size: 6686316 # 6.69 MB
  sys allocs: 24
  sys reallocs: 0
  sys deallocs: 24
  sys alloc bytes: 5512934 # 5.51 MB
  sys peak growth: 5441278 # 5.44 MB
  arena allocs: 0
  arena reallocs: 0
  arena size: 26226448 # 26.23 MB

binder.ts:
  file size: 193077 # 193.08 kB
  sys allocs: 14
  sys reallocs: 0
  sys deallocs: 14
  sys alloc bytes: 247026 # 247.03 kB
  sys peak growth: 246886 # 246.89 kB
  arena allocs: 0
  arena reallocs: 0
  arena size: 815560 # 815.56 kB

kitchen-sink.tsx:
  file size: 732898 # 732.90 kB
  sys allocs: 33
  sys reallocs: 0
  sys deallocs: 33
  sys alloc bytes: 1103942 # 1.10 MB
  sys peak growth: 1101954 # 1.10 MB
  arena allocs: 0
  arena reallocs: 0
  arena size: 5977416 # 5.98 MB

