checker.ts:
  file size: 2922154 # 2.92 MB
  sys allocs: 41
  sys reallocs: 60
  sys deallocs: 41
  sys alloc bytes: 124788 # 124.79 kB
  sys peak growth: 121360 # 121.36 kB
  arena allocs: 264054
  arena reallocs: 135
  arena size: 11835184 # 11.84 MB

App.tsx:
  file size: 415342 # 415.34 kB
  sys allocs: 42
  sys reallocs: 52
  sys deallocs: 42
  sys alloc bytes: 56356 # 56.36 kB
  sys peak growth: 43684 # 43.68 kB
  arena allocs: 44444
  arena reallocs: 81
  arena size: 2095184 # 2.10 MB

RadixUIAdoptionSection.jsx:
  file size: 2520 # 2.52 kB
  sys allocs: 8
  sys reallocs: 5
  sys deallocs: 8
  sys alloc bytes: 108 # 108 B
  sys peak growth: 108 # 108 B
  arena allocs: 367
  arena reallocs: 4
  arena size: 18960 # 18.96 kB

pdf.mjs:
  file size: 567296 # 567.30 kB
  sys allocs: 79
  sys reallocs: 103
  sys deallocs: 79
  sys alloc bytes: 47060 # 47.06 kB
  sys peak growth: 26348 # 26.35 kB
  arena allocs: 90583
  arena reallocs: 218
  arena size: 4153800 # 4.15 MB

antd.js:
  file size: 6686316 # 6.69 MB
  sys allocs: 200
  sys reallocs: 261
  sys deallocs: 200
  sys alloc bytes: 206080 # 206.08 kB
  sys peak growth: 143752 # 143.75 kB
  arena allocs: 528577
  arena reallocs: 1285
  arena size: 26226448 # 26.23 MB

binder.ts:
  file size: 193077 # 193.08 kB
  sys allocs: 15
  sys reallocs: 25
  sys deallocs: 15
  sys alloc bytes: 22252 # 22.25 kB
  sys peak growth: 22252 # 22.25 kB
  arena allocs: 16608
  arena reallocs: 24
  arena size: 815560 # 815.56 kB

kitchen-sink.tsx:
  file size: 732898 # 732.90 kB
  sys allocs: 213
  sys reallocs: 212
  sys deallocs: 213
  sys alloc bytes: 136149 # 136.15 kB
  sys peak growth: 95632 # 95.63 kB
  arena allocs: 137773
  arena reallocs: 658
  arena size: 5977416 # 5.98 MB

