checker.ts:
  file size: 2922154 # 2.92 MB
  sys allocs: 11027
  sys reallocs: 560
  sys deallocs: 11026
  sys alloc bytes: 6131149 # 6.13 MB
  sys peak growth: 2990058 # 2.99 MB
  arena allocs: 1079319
  arena reallocs: 3951
  arena size: 116637808 # 116.64 MB

App.tsx:
  file size: 415342 # 415.34 kB
  sys allocs: 2544
  sys reallocs: 149
  sys deallocs: 2543
  sys alloc bytes: 1542526 # 1.54 MB
  sys peak growth: 582900 # 582.90 kB
  arena allocs: 211998
  arena reallocs: 1679
  arena size: 22302080 # 22.30 MB

RadixUIAdoptionSection.jsx:
  file size: 2520 # 2.52 kB
  sys allocs: 57
  sys reallocs: 31
  sys deallocs: 56
  sys alloc bytes: 15492 # 15.49 kB
  sys peak growth: 7208 # 7.21 kB
  arena allocs: 1155
  arena reallocs: 69
  arena size: 169128 # 169.13 kB

pdf.mjs:
  file size: 567296 # 567.30 kB
  sys allocs: 4031
  sys reallocs: 250
  sys deallocs: 4030
  sys alloc bytes: 3057776 # 3.06 MB
  sys peak growth: 1164624 # 1.16 MB
  arena allocs: 434612
  arena reallocs: 5696
  arena size: 36857064 # 36.86 MB

antd.js:
  file size: 6686316 # 6.69 MB
  sys allocs: 34143
  sys reallocs: 4138
  sys deallocs: 34142
  sys alloc bytes: 105935484 # 105.94 MB
  sys peak growth: 85678576 # 85.68 MB
  arena allocs: 2559844
  arena reallocs: 14941
  arena size: 332361480 # 332.36 MB

binder.ts:
  file size: 193077 # 193.08 kB
  sys allocs: 464
  sys reallocs: 61
  sys deallocs: 463
  sys alloc bytes: 315013 # 315.01 kB
  sys peak growth: 195661 # 195.66 kB
  arena allocs: 64023
  arena reallocs: 244
  arena size: 7370072 # 7.37 MB

kitchen-sink.tsx:
  file size: 732898 # 732.90 kB
  sys allocs: 9578
  sys reallocs: 2876
  sys deallocs: 9577
  sys alloc bytes: 3308148 # 3.31 MB
  sys peak growth: 1499988 # 1.50 MB
  arena allocs: 567769
  arena reallocs: 5992
  arena size: 48529696 # 48.53 MB

