checker.ts:
  file size: 2922154 # 2.92 MB
  sys allocs: 22
  sys reallocs: 10
  sys deallocs: 22
  sys alloc bytes: 10376 # 10.38 kB
  sys peak growth: 8000 # 8 kB
  arena allocs: 262590
  arena reallocs: 22858
  arena size: 13054768 # 13.05 MB

App.tsx:
  file size: 415342 # 415.34 kB
  sys allocs: 20
  sys reallocs: 14
  sys deallocs: 20
  sys alloc bytes: 7492 # 7.49 kB
  sys peak growth: 4132 # 4.13 kB
  arena allocs: 44037
  arena reallocs: 3537
  arena size: 2247136 # 2.25 MB

RadixUIAdoptionSection.jsx:
  file size: 2520 # 2.52 kB
  sys allocs: 1
  sys reallocs: 0
  sys deallocs: 1
  sys alloc bytes: 108 # 108 B
  sys peak growth: 108 # 108 B
  arena allocs: 367
  arena reallocs: 66
  arena size: 21200 # 21.20 kB

pdf.mjs:
  file size: 567296 # 567.30 kB
  sys allocs: 70
  sys reallocs: 67
  sys deallocs: 70
  sys alloc bytes: 29472 # 29.47 kB
  sys peak growth: 11500 # 11.50 kB
  arena allocs: 89857
  arena reallocs: 8136
  arena size: 4553008 # 4.55 MB

antd.js:
  file size: 6686316 # 6.69 MB
  sys allocs: 188
  sys reallocs: 221
  sys deallocs: 188
  sys alloc bytes: 112712 # 112.71 kB
  sys peak growth: 46528 # 46.53 kB
  arena allocs: 528577
  arena reallocs: 55355
  arena size: 30470456 # 30.47 MB

binder.ts:
  file size: 193077 # 193.08 kB
  sys allocs: 0
  sys reallocs: 0
  sys deallocs: 0
  sys alloc bytes: 0 # 0 B
  sys peak growth: 0 # 0 B
  arena allocs: 16587
  arena reallocs: 1476
  arena size: 924032 # 924.03 kB

kitchen-sink.tsx:
  file size: 732898 # 732.90 kB
  sys allocs: 186
  sys reallocs: 160
  sys deallocs: 186
  sys alloc bytes: 37737 # 37.74 kB
  sys peak growth: 5912 # 5.91 kB
  arena allocs: 136453
  arena reallocs: 11898
  arena size: 6456232 # 6.46 MB
