checker.ts:
  file size: 2922154 # 2.92 MB
  sys allocs: 11013
  sys reallocs: 492
  sys deallocs: 11012
  sys alloc bytes: 5918285 # 5.92 MB
  sys peak growth: 2990058 # 2.99 MB
  arena allocs: 1070955
  arena reallocs: 927
  arena size: 115790968 # 115.79 MB

App.tsx:
  file size: 415342 # 415.34 kB
  sys allocs: 2532
  sys reallocs: 85
  sys deallocs: 2531
  sys alloc bytes: 1302622 # 1.30 MB
  sys peak growth: 760990 # 760.99 kB
  arena allocs: 209344
  arena reallocs: 364
  arena size: 21592480 # 21.59 MB

RadixUIAdoptionSection.jsx:
  file size: 2520 # 2.52 kB
  sys allocs: 54
  sys reallocs: 26
  sys deallocs: 53
  sys alloc bytes: 10116 # 10.12 kB
  sys peak growth: 2856 # 2.86 kB
  arena allocs: 1134
  arena reallocs: 0
  arena size: 154768 # 154.77 kB

pdf.mjs:
  file size: 567296 # 567.30 kB
  sys allocs: 4019
  sys reallocs: 173
  sys deallocs: 4018
  sys alloc bytes: 2377712 # 2.38 MB
  sys peak growth: 1492304 # 1.49 MB
  arena allocs: 428857
  arena reallocs: 428
  arena size: 35654864 # 35.65 MB

antd.js:
  file size: 6686316 # 6.69 MB
  sys allocs: 34121
  sys reallocs: 4001
  sys deallocs: 34121
  sys alloc bytes: 104081116 # 104.08 MB
  sys peak growth: 83833168 # 83.83 MB
  arena allocs: 2503924
  arena reallocs: 1889
  arena size: 327824560 # 327.82 MB

binder.ts:
  file size: 193077 # 193.08 kB
  sys allocs: 457
  sys reallocs: 35
  sys deallocs: 456
  sys alloc bytes: 291781 # 291.78 kB
  sys peak growth: 195661 # 195.66 kB
  arena allocs: 63509
  arena reallocs: 38
  arena size: 7297672 # 7.30 MB

kitchen-sink.tsx:
  file size: 732898 # 732.90 kB
  sys allocs: 9566
  sys reallocs: 2822
  sys deallocs: 9564
  sys alloc bytes: 3180244 # 3.18 MB
  sys peak growth: 1520468 # 1.52 MB
  arena allocs: 560401
  arena reallocs: 1041
  arena size: 46408496 # 46.41 MB

