checker.ts:
  file size: 2922154 # 2.92 MB
  sys allocs: 19
  sys reallocs: 10
  sys deallocs: 19
  sys alloc bytes: 2748 # 2.75 kB
  sys peak growth: 2432 # 2.43 kB
  arena allocs: 264846
  arena reallocs: 23773
  arena size: 13612720 # 13.61 MB

App.tsx:
  file size: 415342 # 415.34 kB
  sys allocs: 18
  sys reallocs: 13
  sys deallocs: 18
  sys alloc bytes: 4348 # 4.35 kB
  sys peak growth: 1868 # 1.87 kB
  arena allocs: 44301
  arena reallocs: 3651
  arena size: 2316096 # 2.32 MB

RadixUIAdoptionSection.jsx:
  file size: 2520 # 2.52 kB
  sys allocs: 1
  sys reallocs: 0
  sys deallocs: 1
  sys alloc bytes: 108 # 108 B
  sys peak growth: 108 # 108 B
  arena allocs: 371
  arena reallocs: 66
  arena size: 21200 # 21.20 kB

pdf.mjs:
  file size: 567296 # 567.30 kB
  sys allocs: 67
  sys reallocs: 67
  sys deallocs: 67
  sys alloc bytes: 24020 # 24.02 kB
  sys peak growth: 12140 # 12.14 kB
  arena allocs: 90100
  arena reallocs: 8152
  arena size: 4621456 # 4.62 MB

antd.js:
  file size: 6686316 # 6.69 MB
  sys allocs: 185
  sys reallocs: 221
  sys deallocs: 185
  sys alloc bytes: 107804 # 107.80 kB
  sys peak growth: 48264 # 48.26 kB
  arena allocs: 543758
  arena reallocs: 56417
  arena size: 34852280 # 34.85 MB

binder.ts:
  file size: 193077 # 193.08 kB
  sys allocs: 0
  sys reallocs: 0
  sys deallocs: 0
  sys alloc bytes: 3016 # 3.02 kB
  sys peak growth: 251 # 251 B
  arena allocs: 16757
  arena reallocs: 1547
  arena size: 959248 # 959.25 kB

kitchen-sink.tsx:
  file size: 732898 # 732.90 kB
  sys allocs: 183
  sys reallocs: 160
  sys deallocs: 183
  sys alloc bytes: 34053 # 34.05 kB
  sys peak growth: 3892 # 3.89 kB
  arena allocs: 136770
  arena reallocs: 12040
  arena size: 6526752 # 6.53 MB
