checker.ts:
  file size: 2922154 # 2.92 MB
  sys allocs: 152
  sys reallocs: 5
  sys deallocs: 152
  sys alloc bytes: 15030872 # 15.03 MB
  sys peak growth: 10203896 # 10.20 MB
  arena allocs: 152956
  arena reallocs: 28386
  arena size: 19332672 # 19.33 MB

App.tsx:
  file size: 415342 # 415.34 kB
  sys allocs: 63
  sys reallocs: 8
  sys deallocs: 63
  sys alloc bytes: 2136669 # 2.14 MB
  sys peak growth: 1620605 # 1.62 MB
  arena allocs: 17035
  arena reallocs: 2714
  arena size: 2916824 # 2.92 MB

RadixUIAdoptionSection.jsx:
  file size: 2520 # 2.52 kB
  sys allocs: 21
  sys reallocs: 0
  sys deallocs: 21
  sys alloc bytes: 17368 # 17.37 kB
  sys peak growth: 11628 # 11.63 kB
  arena allocs: 33
  arena reallocs: 6
  arena size: 35768 # 35.77 kB

pdf.mjs:
  file size: 567296 # 567.30 kB
  sys allocs: 2467
  sys reallocs: 205
  sys deallocs: 2467
  sys alloc bytes: 5348219 # 5.35 MB
  sys peak growth: 3707391 # 3.71 MB
  arena allocs: 47436
  arena reallocs: 7715
  arena size: 6374320 # 6.37 MB

antd.js:
  file size: 6686316 # 6.69 MB
  sys allocs: 1038
  sys reallocs: 56
  sys deallocs: 1038
  sys alloc bytes: 29975903 # 29.98 MB
  sys peak growth: 19934725 # 19.93 MB
  arena allocs: 371546
  arena reallocs: 76276
  arena size: 49106184 # 49.11 MB

binder.ts:
  file size: 193077 # 193.08 kB
  sys allocs: 33
  sys reallocs: 1
  sys deallocs: 33
  sys alloc bytes: 963614 # 963.61 kB
  sys peak growth: 658042 # 658.04 kB
  arena allocs: 7078
  arena reallocs: 841
  arena size: 1169840 # 1.17 MB

kitchen-sink.tsx:
  file size: 732898 # 732.90 kB
  sys allocs: 1858
  sys reallocs: 174
  sys deallocs: 1858
  sys alloc bytes: 5337950 # 5.34 MB
  sys peak growth: 3737991 # 3.74 MB
  arena allocs: 71873
  arena reallocs: 12252
  arena size: 9559192 # 9.56 MB

