checker.ts:
  file size: 2922154 # 2.92 MB
  sys allocs: 309
  sys reallocs: 23
  sys deallocs: 309
  sys alloc bytes: 15428192 # 15.43 MB
  sys peak growth: 10253324 # 10.25 MB
  arena allocs: 151270
  arena reallocs: 29200
  arena size: 22587904 # 22.59 MB

App.tsx:
  file size: 415342 # 415.34 kB
  sys allocs: 123
  sys reallocs: 8
  sys deallocs: 123
  sys alloc bytes: 2179651 # 2.18 MB
  sys peak growth: 1622499 # 1.62 MB
  arena allocs: 16423
  arena reallocs: 2819
  arena size: 3308764 # 3.31 MB

RadixUIAdoptionSection.jsx:
  file size: 2520 # 2.52 kB
  sys allocs: 21
  sys reallocs: 0
  sys deallocs: 21
  sys alloc bytes: 17400 # 17.40 kB
  sys peak growth: 11628 # 11.63 kB
  arena allocs: 29
  arena reallocs: 6
  arena size: 35632 # 35.63 kB

pdf.mjs:
  file size: 567296 # 567.30 kB
  sys allocs: 2496
  sys reallocs: 205
  sys deallocs: 2496
  sys alloc bytes: 5392831 # 5.39 MB
  sys peak growth: 3712575 # 3.71 MB
  arena allocs: 46029
  arena reallocs: 7746
  arena size: 7068920 # 7.07 MB

antd.js:
  file size: 6686316 # 6.69 MB
  sys allocs: 1180
  sys reallocs: 56
  sys deallocs: 1180
  sys alloc bytes: 34472535 # 34.47 MB
  sys peak growth: 20584457 # 20.58 MB
  arena allocs: 413528
  arena reallocs: 76626
  arena size: 92372080 # 92.37 MB

binder.ts:
  file size: 193077 # 193.08 kB
  sys allocs: 94
  sys reallocs: 1
  sys deallocs: 94
  sys alloc bytes: 999080 # 999.08 kB
  sys peak growth: 662488 # 662.49 kB
  arena allocs: 7295
  arena reallocs: 947
  arena size: 1422088 # 1.42 MB

kitchen-sink.tsx:
  file size: 732898 # 732.90 kB
  sys allocs: 1919
  sys reallocs: 174
  sys deallocs: 1919
  sys alloc bytes: 5337300 # 5.34 MB
  sys peak growth: 3710713 # 3.71 MB
  arena allocs: 65355
  arena reallocs: 12268
  arena size: 9723728 # 9.72 MB
