checker.ts:
  file size: 2922154 # 2.92 MB
  sys allocs: 43
  sys reallocs: 0
  sys deallocs: 69
  sys alloc bytes: 50059 # 50.06 kB
  sys peak growth: 29451 # 29.45 kB
  arena allocs: 1959
  arena reallocs: 5
  arena size: 13012200 # 13.01 MB

App.tsx:
  file size: 415342 # 415.34 kB
  sys allocs: 38
  sys reallocs: 2
  sys deallocs: 43
  sys alloc bytes: 8600 # 8.60 kB
  sys peak growth: 2584 # 2.58 kB
  arena allocs: 618
  arena reallocs: 17
  arena size: 2264144 # 2.26 MB

RadixUIAdoptionSection.jsx:
  file size: 2520 # 2.52 kB
  sys allocs: 19
  sys reallocs: 2
  sys deallocs: 24
  sys alloc bytes: 2208 # 2.21 kB
  sys peak growth: 2144 # 2.14 kB
  arena allocs: 258
  arena reallocs: 13
  arena size: 34616 # 34.62 kB

pdf.mjs:
  file size: 567296 # 567.30 kB
  sys allocs: 13
  sys reallocs: 0
  sys deallocs: 18
  sys alloc bytes: 1610 # 1.61 kB
  sys peak growth: 1610 # 1.61 kB
  arena allocs: 2
  arena reallocs: 0
  arena size: 4536736 # 4.54 MB

antd.js:
  file size: 6686316 # 6.69 MB
  sys allocs: 13
  sys reallocs: 0
  sys deallocs: 19
  sys alloc bytes: 1611 # 1.61 kB
  sys peak growth: 1611 # 1.61 kB
  arena allocs: 2
  arena reallocs: 0
  arena size: 29421944 # 29.42 MB

binder.ts:
  file size: 193077 # 193.08 kB
  sys allocs: 31
  sys reallocs: 0
  sys deallocs: 41
  sys alloc bytes: 12989 # 12.99 kB
  sys peak growth: 8217 # 8.22 kB
  arena allocs: 154
  arena reallocs: 0
  arena size: 923168 # 923.17 kB

kitchen-sink.tsx:
  file size: 732898 # 732.90 kB
  sys allocs: 212
  sys reallocs: 3
  sys deallocs: 226
  sys alloc bytes: 127518 # 127.52 kB
  sys peak growth: 64934 # 64.93 kB
  arena allocs: 6132
  arena reallocs: 280
  arena size: 6774200 # 6.77 MB
