/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Register a JS runner function.
 * Called from a JS worker thread.
 */
export declare function registerWorker(workerId: number, run: () => void): void

/**
 * Entry point from JS.
 *
 * * Determines number of threads to use.
 * * Calls JS `startWorkers` function to start up worker threads
 *   (those worker threads each call `register_worker` when they start up).
 * * Runs workload.
 */
export declare function run(startWorkers: StartThreads): Promise<boolean>
