//! Relay `graphql` tagged template transform.
//!
//! Replaces `graphql` tagged template expressions with references to the
//! artifact files generated by `relay-compiler`:
//!
//! ```js
//! const data = graphql`query FooQuery { id }`;
//! ```
//!
//! becomes (with `eager_es_modules: true`, the default):
//!
//! ```js
//! import _FooQuery from "./__generated__/FooQuery.graphql.js";
//! const data = _FooQuery;
//! ```
//!
//! or (with `eager_es_modules: false`):
//!
//! ```js
//! const data = require("./__generated__/FooQuery.graphql.js");
//! ```
//!
//! Port of [babel-plugin-relay] and [swc_relay].
//!
//! Not supported compared to `babel-plugin-relay`: development-mode artifact
//! hash validation, `jsModuleFormat: "haste"`, `isDevVariableName`, and GraphQL
//! document validation (the definition name is extracted textually, like
//! `swc_relay`, rather than by parsing the document).
//!
//! [babel-plugin-relay]: https://github.com/facebook/relay/tree/main/packages/babel-plugin-relay
//! [swc_relay]: https://github.com/swc-project/plugins/tree/main/packages/relay

use std::path::{Path, PathBuf};

use oxc_allocator::{Allocator, ArenaVec};
use oxc_ast::ast::*;
use oxc_diagnostics::{Diagnostics, OxcDiagnostic};
use oxc_semantic::{ReferenceFlags, Scoping, SymbolFlags};
use oxc_span::SPAN;
use oxc_str::{Str, static_ident};
use oxc_traverse::{BoundIdentifier, Traverse, traverse_mut};

type TraverseCtx<'a> = oxc_traverse::TraverseCtx<'a, ()>;

/// The language `relay-compiler` emits artifacts in, which determines the
/// artifact file extension (`.graphql.ts` for TypeScript, `.graphql.js`
/// otherwise).
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum RelayLanguage {
    /// `Name.graphql.ts` artifacts.
    Typescript,
    /// `Name.graphql.js` artifacts.
    #[default]
    Javascript,
    /// `Name.graphql.js` artifacts.
    Flow,
}

/// Options for the Relay transform.
///
/// Mirrors the options of `babel-plugin-relay` / `@swc/plugin-relay`.
#[derive(Debug, Clone)]
pub struct RelayOptions {
    /// Directory `relay-compiler` emits all artifacts to (its
    /// `artifactDirectory` setting). When set, artifacts are imported via a
    /// relative path from the file being transformed to this directory; the
    /// path is computed lexically, so both must either be absolute or relative
    /// to the same base directory. When unset, artifacts are imported from the
    /// `__generated__` directory next to the file being transformed.
    pub artifact_directory: Option<PathBuf>,

    /// Artifact language, determining the imported file extension.
    ///
    /// Defaults to [`RelayLanguage::Javascript`].
    pub language: RelayLanguage,

    /// Emit a hoisted default import per `graphql` tag instead of an inline
    /// `require()` call.
    ///
    /// Defaults to `true`, matching `babel-plugin-relay` since Relay v17.
    /// `@swc/plugin-relay` and Next.js default to `false`.
    pub eager_es_modules: bool,
}

impl Default for RelayOptions {
    fn default() -> Self {
        Self {
            artifact_directory: None,
            language: RelayLanguage::default(),
            eager_es_modules: true,
        }
    }
}

/// Result of [`Relay::build`].
#[must_use]
pub struct RelayReturn {
    /// Scoping returned from the traversal.
    pub scoping: Scoping,
    /// Errors for `graphql` tags no definition name could be extracted from.
    pub diagnostics: Diagnostics,
}

/// Relay `graphql` tagged template transform.
///
/// ## Example
///
/// ```rust,ignore
/// let ret = Relay::new(RelayOptions::default(), Path::new("src/Foo.jsx"))
///     .build(&allocator, &mut program, scoping);
/// ```
pub struct Relay<'a> {
    options: RelayOptions,
    /// Lexical relative path from the transformed file's directory to
    /// `artifact_directory`, precomputed with POSIX separators.
    /// `None` when `artifact_directory` is unset.
    relative_artifact_dir: Option<String>,
    /// One entry per transformed `graphql` tag in eager mode, in source order:
    /// the default import binding and the artifact import path.
    imports: Vec<(BoundIdentifier<'a>, Str<'a>)>,
    diagnostics: Diagnostics,
}

impl<'a> Relay<'a> {
    /// Create a new Relay transform for the file at `source_path`.
    ///
    /// `source_path` is only used lexically to compute artifact import paths;
    /// the filesystem is never accessed.
    pub fn new(options: RelayOptions, source_path: &Path) -> Self {
        let relative_artifact_dir = options.artifact_directory.as_ref().map(|artifact_dir| {
            let source_dir = source_path.parent().unwrap_or_else(|| Path::new(""));
            relative_path(&source_dir.to_string_lossy(), &artifact_dir.to_string_lossy())
        });
        Self { options, relative_artifact_dir, imports: vec![], diagnostics: Diagnostics::new() }
    }

    /// Run the transform on `program`.
    pub fn build(
        mut self,
        allocator: &'a Allocator,
        program: &mut Program<'a>,
        scoping: Scoping,
    ) -> RelayReturn {
        let scoping = traverse_mut(&mut self, allocator, program, scoping, ());
        RelayReturn { scoping, diagnostics: self.diagnostics }
    }

    /// Import path for the artifact of the GraphQL definition `name`.
    fn artifact_import_path(&self, name: &str) -> String {
        let extension = match self.options.language {
            RelayLanguage::Typescript => "ts",
            RelayLanguage::Javascript | RelayLanguage::Flow => "js",
        };
        match self.relative_artifact_dir.as_deref() {
            None => format!("./__generated__/{name}.graphql.{extension}"),
            Some(".") => format!("./{name}.graphql.{extension}"),
            // Like `babel-plugin-relay`, paths already starting with `.`
            // (i.e. `..`) are used as-is; everything else gets a `./` prefix.
            Some(dir) if dir.starts_with('.') => format!("{dir}/{name}.graphql.{extension}"),
            Some(dir) => format!("./{dir}/{name}.graphql.{extension}"),
        }
    }
}

impl<'a> Traverse<'a, ()> for Relay<'a> {
    #[inline] // Fast path: most expressions are not tagged templates.
    fn enter_expression(&mut self, expr: &mut Expression<'a>, ctx: &mut TraverseCtx<'a>) {
        let Expression::TaggedTemplateExpression(tagged) = expr else { return };
        let Expression::Identifier(tag) = &tagged.tag else { return };
        if tag.name != "graphql" {
            return;
        }

        let span = tagged.span;
        // `Str::as_str` returns `&'a str` borrowed from the arena, not from
        // `tagged`, so `name` stays valid while `*expr` is replaced below.
        let Some(name) = extract_definition_name(&tagged.quasi) else {
            self.diagnostics.push(
                OxcDiagnostic::error(
                    "`graphql` tagged template must contain a named GraphQL query, mutation, subscription, or fragment",
                )
                .with_label(span),
            );
            return;
        };

        let source = Str::from_str_in(&self.artifact_import_path(name), ctx);
        *expr = if self.options.eager_es_modules {
            let binding = ctx.generate_uid_in_root_scope(name, SymbolFlags::Import);
            let reference = binding.create_spanned_read_expression(span, ctx);
            self.imports.push((binding, source));
            reference
        } else {
            let callee =
                ctx.create_unbound_ident_expr(SPAN, static_ident!("require"), ReferenceFlags::Read);
            let argument = Argument::new_string_literal(SPAN, source, None, ctx);
            Expression::new_call_expression(span, callee, None, [argument], false, ctx)
        };
    }

    fn exit_program(&mut self, program: &mut Program<'a>, ctx: &mut TraverseCtx<'a>) {
        if self.imports.is_empty() {
            return;
        }
        // `import <uid> from "<artifact path>";`, one per `graphql` tag.
        let imports = self.imports.drain(..).map(|(binding, source)| {
            let local = binding.create_binding_identifier(ctx);
            let specifier =
                ImportDeclarationSpecifier::new_import_default_specifier(SPAN, local, ctx);
            let specifiers = Some(ArenaVec::from_value_in(specifier, ctx));
            let source = StringLiteral::new(SPAN, source, None, ctx);
            Statement::new_import_declaration(
                SPAN,
                specifiers,
                source,
                None,
                None,
                ImportOrExportKind::Value,
                ctx,
            )
        });
        program.body.splice(0..0, imports);
    }
}

/// Find the first GraphQL definition name across the template's quasis.
fn extract_definition_name<'a>(template: &TemplateLiteral<'a>) -> Option<&'a str> {
    template.quasis.iter().find_map(|quasi| find_definition_name(quasi.value.raw.as_str()))
}

const KEYWORDS: [&str; 4] = ["fragment", "mutation", "query", "subscription"];

fn is_word_byte(byte: u8) -> bool {
    byte == b'_' || byte.is_ascii_alphanumeric()
}

/// Find the first GraphQL definition name in `text`.
///
/// Equivalent to stripping `#` line comments and matching
/// `\b(fragment|mutation|query|subscription)\s+(\w+)`, like `swc_relay`,
/// without allocating. Byte scanning is UTF-8 safe: slices are only taken at
/// ASCII word-run boundaries, which are always character boundaries.
fn find_definition_name(text: &str) -> Option<&str> {
    let bytes = text.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'#' {
            // Comment: skip to the end of the line.
            while i < bytes.len() && bytes[i] != b'\n' {
                i += 1;
            }
        } else if is_word_byte(bytes[i]) {
            // Consuming maximal word runs guarantees a word boundary on both
            // sides of the keyword.
            let start = i;
            while i < bytes.len() && is_word_byte(bytes[i]) {
                i += 1;
            }
            if !KEYWORDS.contains(&&text[start..i]) {
                continue;
            }
            // Consume the whitespace (and comments) separating the keyword
            // from the name; at least one whitespace character is required.
            let mut separated = false;
            while i < bytes.len() {
                if bytes[i] == b'#' {
                    while i < bytes.len() && bytes[i] != b'\n' {
                        i += 1;
                    }
                } else if bytes[i].is_ascii_whitespace() {
                    separated = true;
                    i += 1;
                } else {
                    break;
                }
            }
            if separated && i < bytes.len() && is_word_byte(bytes[i]) {
                let name_start = i;
                while i < bytes.len() && is_word_byte(bytes[i]) {
                    i += 1;
                }
                return Some(&text[name_start..i]);
            }
        } else {
            i += 1;
        }
    }
    None
}

/// Lexical relative path from directory `from` to directory `to`, with POSIX
/// separators.
///
/// Pure string computation — the filesystem is never accessed, so both paths
/// must either be absolute or relative to the same base directory. Accepts `/`
/// and `\` as input separators.
fn relative_path(from: &str, to: &str) -> String {
    let from = normalize(from);
    let to = normalize(to);
    let is_windows = from.first().is_some_and(|component| is_windows_drive(component))
        && to.first().is_some_and(|component| is_windows_drive(component));
    let common = from
        .iter()
        .zip(&to)
        .take_while(|(a, b)| if is_windows { a.eq_ignore_ascii_case(b) } else { a == b })
        .count();
    let mut components = vec![".."; from.len() - common];
    components.extend_from_slice(&to[common..]);
    if components.is_empty() { ".".to_string() } else { components.join("/") }
}

fn is_windows_drive(component: &str) -> bool {
    matches!(component.as_bytes(), [drive, b':'] if drive.is_ascii_alphabetic())
}

/// Split a path into components, dropping `.` and folding `..`.
fn normalize(path: &str) -> Vec<&str> {
    let mut components: Vec<&str> = vec![];
    for component in path.split(['/', '\\']) {
        match component {
            "" | "." => {}
            ".." => {
                if components.last().is_none_or(|&last| last == "..") {
                    components.push("..");
                } else {
                    components.pop();
                }
            }
            _ => components.push(component),
        }
    }
    components
}

#[cfg(test)]
mod test {
    use super::{find_definition_name, relative_path};

    #[test]
    fn definition_name() {
        assert_eq!(find_definition_name("query FooQuery { id }"), Some("FooQuery"));
        assert_eq!(find_definition_name("fragment Foo_bar on User { id }"), Some("Foo_bar"));
        assert_eq!(find_definition_name("# query Hidden\nquery Real { id }"), Some("Real"));
        assert_eq!(find_definition_name("query { id }"), None);
        assert_eq!(find_definition_name("myquery Foo { id }"), None);
    }

    #[test]
    fn relative_paths() {
        assert_eq!(relative_path("/a/b", "/a/b"), ".");
        assert_eq!(relative_path("/a/b/c", "/a/d/e"), "../../d/e");
        assert_eq!(relative_path("src/pages", "src/__generated__"), "../__generated__");
        assert_eq!(relative_path("C:\\a\\b", "C:\\a\\c"), "../c");
        assert_eq!(relative_path("C:\\Repo\\src", "c:\\repo\\src\\__generated__"), "__generated__");
    }
}
