use schemars::{
    r#gen::SchemaGenerator,
    schema::{InstanceType, ObjectValidation, Schema, SchemaObject, SubschemaValidation},
};

#[cfg(feature = "ruledocs")]
use schemars::schema::NumberValidation;

#[cfg(feature = "ruledocs")]
use crate::rules::RuleEnum;

/// These rules are not verified to have a valid schema
/// These should return the DummyRule struct/schema instead of the actual rule struct/schema,
/// until we verify that the rule's schema is valid and can be generated by schemars.
#[cfg(feature = "ruledocs")]
const NO_VERIFIED_VALID_SCHEMA: [&str; 14] = [
    "eslint/no-restricted-globals", // uses spread syntax like [AllowWarnDeny, ...Config]
    "eslint/no-restricted-imports", // uses spread syntax like [AllowWarnDeny, ...Config]
    "eslint/no-restricted-properties", // uses spread syntax like [AllowWarnDeny, ...Config]
    "node/callback-return",         // uses array syntax [AllowWarnDeny, string[]]
    "jest/prefer-lowercase-title",  // has options from other rule #23186
    "jest/valid-title",             // has options from other rule #23186
    "vitest/prefer-lowercase-title", // has options from other rule #23186
    "vitest/valid-title",           // has options from other rule #23186
    "jsdoc/require-param",          // missing options #23356
    "unicorn/filename-case",        // missing options #23248
    "unicorn/numeric-separators-style", // missing options #23383
    "jsx_a11y/no-noninteractive-element-interactions", // TS Generation generates ts 2411 error
    "eslint/prefer-destructuring",
    "import/extensions",
];

/// Should this rule be skipped for config schema generation?
/// We skip rules that don't have verified valid schemas to avoid generating invalid schemas.
#[cfg(feature = "ruledocs")]
pub fn should_skip_config_schema(rule_name: &RuleEnum) -> bool {
    let name = format!("{}/{}", rule_name.plugin_name(), rule_name.name());
    NO_VERIFIED_VALID_SCHEMA.contains(&name.as_str())
}

/// Generates a JSON schema for an object where the keys are strings and the values are either strings or null.
/// TS type equivalent: `Record<string, string | null>`
pub fn object_with_nullable_string_schema(_gen: &mut SchemaGenerator) -> Schema {
    let value_schema = SchemaObject {
        subschemas: Some(Box::new(SubschemaValidation {
            any_of: Some(vec![
                SchemaObject {
                    instance_type: Some(InstanceType::String.into()),
                    ..Default::default()
                }
                .into(),
                SchemaObject {
                    instance_type: Some(InstanceType::Null.into()),
                    ..Default::default()
                }
                .into(),
            ]),
            ..Default::default()
        })),
        ..Default::default()
    };

    SchemaObject {
        instance_type: Some(InstanceType::Object.into()),
        object: Some(Box::new(ObjectValidation {
            additional_properties: Some(Box::new(value_schema.into())),
            ..Default::default()
        })),
        ..Default::default()
    }
    .into()
}

/// Converts an object schema into a schema that accepts both numbers and objects.
/// Optionally, a number validation can be provided to further restrict the accepted values.
#[cfg(feature = "ruledocs")]
pub fn number_as_object_schema(
    _gen: &mut SchemaGenerator,
    schema: &mut Schema,
    number_schema: Option<NumberValidation>,
) {
    let Schema::Object(object_schema) = schema.clone() else {
        panic!("Expected an object schema to be converted");
    };

    let number_only_schema = SchemaObject {
        instance_type: Some(InstanceType::Number.into()),
        number: number_schema.map(Box::new),
        ..Default::default()
    };

    *schema = SchemaObject {
        subschemas: Some(Box::new(SubschemaValidation {
            any_of: Some(vec![number_only_schema.into(), Schema::Object(object_schema)]),
            ..Default::default()
        })),
        ..Default::default()
    }
    .into();
}
