use schemars::{
    r#gen::SchemaGenerator,
    schema::{InstanceType, ObjectValidation, Schema, SchemaObject, SubschemaValidation},
};

#[cfg(feature = "ruledocs")]
use schemars::schema::NumberValidation;

#[cfg(feature = "ruledocs")]
use crate::rules::RuleEnum;

/// These rules are not verified to have a valid schema
/// These should return the DummyRule struct/schema instead of the actual rule struct/schema,
/// until we verify that the rule's schema is valid and can be generated by schemars.
#[cfg(feature = "ruledocs")]
const NO_VERIFIED_VALID_SCHEMA: [&str; 111] = [
    "eslint/capitalized-comments",
    "eslint/class-methods-use-this",
    "eslint/complexity",
    "eslint/id-length",
    "eslint/id-match",
    "eslint/no-empty-function",
    "eslint/no-constant-condition",
    "eslint/no-inner-declarations",
    "eslint/no-magic-numbers",
    "eslint/no-param-reassign",
    "eslint/no-restricted-exports",
    "eslint/no-restricted-globals",
    "eslint/no-restricted-imports",
    "eslint/no-restricted-properties",
    "eslint/no-shadow",
    "eslint/no-unused-vars",
    "eslint/no-use-before-define",
    "eslint/no-warning-comments",
    "eslint/operator-assignment",
    "eslint/prefer-destructuring",
    "eslint/prefer-const",
    "eslint/radix",
    "eslint/sort-vars",
    "import/extensions",
    "import/prefer-default-export",
    "import/max-dependencies",
    "jest/consistent-test-it",
    "jest/expect-expect",
    "jest/max-expects",
    "jest/max-nested-describe",
    "jest/no-deprecated-functions",
    "jest/no-hooks",
    "jest/no-large-snapshots",
    "jest/no-restricted-jest-methods",
    "jest/no-restricted-matchers",
    "jest/no-standalone-expect",
    "jest/prefer-ending-with-an-expect",
    "jest/prefer-expect-assertions",
    "jest/prefer-lowercase-title",
    "jest/prefer-snapshot-hint",
    "jest/require-top-level-describe",
    "jest/valid-expect",
    "jest/valid-title",
    "jsdoc/require-param",
    "jsx_a11y/alt-text",
    "jsx_a11y/anchor-is-valid",
    "jsx_a11y/control-has-associated-label",
    "jsx_a11y/img-redundant-alt",
    "jsx_a11y/label-has-associated-control",
    "jsx_a11y/media-has-caption",
    "jsx_a11y/no-distracting-elements",
    "jsx_a11y/no-noninteractive-element-to-interactive-role",
    "jsx_a11y/no-interactive-element-to-noninteractive-role",
    "jsx_a11y/no-noninteractive-element-interactions",
    "jsx_a11y/no-noninteractive-tabindex",
    "oxc/no-async-endpoint-handlers",
    "promise/catch-or-return",
    "promise/no-callback-in-promise",
    "promise/param-names",
    "react/exhaustive-deps",
    "react/jsx-curly-brace-presence",
    "react/jsx-filename-extension",
    "react/jsx-handler-names",
    "react/jsx-no-script-url",
    "react/jsx-no-target-blank",
    "react/jsx-props-no-spreading",
    "react/no-did-update-set-state",
    "react/no-object-type-as-default-prop",
    "react/no-unstable-nested-components",
    "react_perf/jsx-no-new-object-as-prop",
    "typescript/array-type",
    "typescript/ban-ts-comment",
    "typescript/consistent-generic-constructors",
    "typescript/consistent-type-imports",
    "typescript/no-empty-object-type",
    "typescript/no-duplicate-type-constituents",
    "typescript/no-invalid-void-type",
    "typescript/no-misused-promises",
    "typescript/no-unnecessary-condition",
    "typescript/no-restricted-types",
    "typescript/parameter-properties",
    "typescript/prefer-nullish-coalescing",
    "typescript/prefer-string-starts-ends-with",
    "typescript/triple-slash-reference",
    "unicorn/catch-error-name",
    "unicorn/explicit-length-check",
    "unicorn/filename-case",
    "unicorn/no-instanceof-builtins",
    "unicorn/numeric-separators-style",
    "unicorn/prefer-at",
    "unicorn/prefer-object-from-entries",
    "vitest/consistent-each-for",
    "vitest/consistent-test-filename",
    "vitest/consistent-test-it",
    "vitest/consistent-vitest-vi",
    "vitest/expect-expect",
    "vitest/max-expects",
    "vitest/max-nested-describe",
    "vitest/no-hooks",
    "vitest/no-large-snapshots",
    "vitest/no-restricted-matchers",
    "vitest/no-restricted-vi-methods",
    "vitest/no-standalone-expect",
    "vitest/prefer-expect-assertions",
    "vitest/prefer-import-in-mock",
    "vitest/prefer-lowercase-title",
    "vitest/prefer-snapshot-hint",
    "vitest/require-top-level-describe",
    "vitest/valid-expect",
    "vitest/valid-title",
    "vue/define-props-destructuring",
];

/// Should this rule be skipped for config schema generation?
/// We skip rules that don't have verified valid schemas to avoid generating invalid schemas.
#[cfg(feature = "ruledocs")]
pub fn should_skip_config_schema(rule_name: &RuleEnum) -> bool {
    let name = format!("{}/{}", rule_name.plugin_name(), rule_name.name());
    NO_VERIFIED_VALID_SCHEMA.contains(&name.as_str())
}

/// Generates a JSON schema for an object where the keys are strings and the values are either strings or null.
/// TS type equivalent: `Record<string, string | null>`
pub fn object_with_nullable_string_schema(_gen: &mut SchemaGenerator) -> Schema {
    let value_schema = SchemaObject {
        subschemas: Some(Box::new(SubschemaValidation {
            any_of: Some(vec![
                SchemaObject {
                    instance_type: Some(InstanceType::String.into()),
                    ..Default::default()
                }
                .into(),
                SchemaObject {
                    instance_type: Some(InstanceType::Null.into()),
                    ..Default::default()
                }
                .into(),
            ]),
            ..Default::default()
        })),
        ..Default::default()
    };

    SchemaObject {
        instance_type: Some(InstanceType::Object.into()),
        object: Some(Box::new(ObjectValidation {
            additional_properties: Some(Box::new(value_schema.into())),
            ..Default::default()
        })),
        ..Default::default()
    }
    .into()
}

/// Converts an object schema into a schema that accepts both numbers and objects.
/// Optionally, a number validation can be provided to further restrict the accepted values.
#[cfg(feature = "ruledocs")]
pub fn number_as_object_schema(
    _gen: &mut SchemaGenerator,
    schema: &mut Schema,
    number_schema: Option<NumberValidation>,
) {
    let Schema::Object(object_schema) = schema.clone() else {
        panic!("Expected an object schema to be converted");
    };

    let number_only_schema = SchemaObject {
        instance_type: Some(InstanceType::Number.into()),
        number: number_schema.map(Box::new),
        ..Default::default()
    };

    *schema = SchemaObject {
        subschemas: Some(Box::new(SubschemaValidation {
            any_of: Some(vec![number_only_schema.into(), Schema::Object(object_schema)]),
            ..Default::default()
        })),
        ..Default::default()
    }
    .into();
}
