use oxc_diagnostics::OxcDiagnostic;

/// ECMAScript target version for compiler options.
///
/// Unlike `oxc_syntax::ESTarget` (used by the transformer pipeline, which
/// does not support ES5), this enum covers the full range of tsc targets
/// and is used for compiler-option validation (e.g. deprecated target warnings).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ScriptTarget {
    ES3,
    ES5,
    ES2015,
    ES2016,
    ES2017,
    ES2018,
    ES2019,
    ES2020,
    ES2021,
    ES2022,
    ES2023,
    ES2024,
    ES2025,
    ES2026,
    ESNext,
}

impl ScriptTarget {
    /// Parse a target string (case-insensitive) into a `ScriptTarget`.
    pub fn from_str_option(s: &str) -> Option<Self> {
        match s.to_ascii_lowercase().as_str() {
            "es3" => Some(Self::ES3),
            "es5" => Some(Self::ES5),
            "es6" | "es2015" => Some(Self::ES2015),
            "es2016" => Some(Self::ES2016),
            "es2017" => Some(Self::ES2017),
            "es2018" => Some(Self::ES2018),
            "es2019" => Some(Self::ES2019),
            "es2020" => Some(Self::ES2020),
            "es2021" => Some(Self::ES2021),
            "es2022" => Some(Self::ES2022),
            "es2023" => Some(Self::ES2023),
            "es2024" => Some(Self::ES2024),
            "es2025" => Some(Self::ES2025),
            "es2026" => Some(Self::ES2026),
            "esnext" => Some(Self::ESNext),
            _ => None,
        }
    }

    /// The canonical display name used in diagnostics (e.g. `"ES5"`).
    pub fn as_str(self) -> &'static str {
        match self {
            Self::ES3 => "ES3",
            Self::ES5 => "ES5",
            Self::ES2015 => "ES2015",
            Self::ES2016 => "ES2016",
            Self::ES2017 => "ES2017",
            Self::ES2018 => "ES2018",
            Self::ES2019 => "ES2019",
            Self::ES2020 => "ES2020",
            Self::ES2021 => "ES2021",
            Self::ES2022 => "ES2022",
            Self::ES2023 => "ES2023",
            Self::ES2024 => "ES2024",
            Self::ES2025 => "ES2025",
            Self::ES2026 => "ES2026",
            Self::ESNext => "ESNext",
        }
    }
    /// Return the list of lib file basenames for this target.
    ///
    /// Each name maps to `lib.{name}.d.ts` on disk. The list is cumulative:
    /// ES2016 includes all ES2015 libs plus the ES2016-specific ones.
    /// This is a hardcoded table matching tsc's built-in mapping, avoiding
    /// the need to parse `/// <reference lib="..." />` directives.
    pub fn default_libs(self) -> &'static [&'static str] {
        // Each target includes everything from the previous target plus
        // its own sub-libs. The arrays are pre-flattened for efficiency.
        match self {
            Self::ES3 | Self::ES5 => &["es5"],
            Self::ES2015 => &[
                "es5",
                "es2015.core",
                "es2015.collection",
                "es2015.iterable",
                "es2015.generator",
                "es2015.promise",
                "es2015.proxy",
                "es2015.reflect",
                "es2015.symbol",
                "es2015.symbol.wellknown",
            ],
            Self::ES2016 => &[
                "es5",
                "es2015.core",
                "es2015.collection",
                "es2015.iterable",
                "es2015.generator",
                "es2015.promise",
                "es2015.proxy",
                "es2015.reflect",
                "es2015.symbol",
                "es2015.symbol.wellknown",
                "es2016.array.include",
                "es2016.intl",
            ],
            Self::ES2017 => &[
                "es5",
                "es2015.core",
                "es2015.collection",
                "es2015.iterable",
                "es2015.generator",
                "es2015.promise",
                "es2015.proxy",
                "es2015.reflect",
                "es2015.symbol",
                "es2015.symbol.wellknown",
                "es2016.array.include",
                "es2016.intl",
                "es2017.arraybuffer",
                "es2017.date",
                "es2017.intl",
                "es2017.object",
                "es2017.sharedmemory",
                "es2017.string",
                "es2017.typedarrays",
            ],
            Self::ES2018 => &[
                "es5",
                "es2015.core",
                "es2015.collection",
                "es2015.iterable",
                "es2015.generator",
                "es2015.promise",
                "es2015.proxy",
                "es2015.reflect",
                "es2015.symbol",
                "es2015.symbol.wellknown",
                "es2016.array.include",
                "es2016.intl",
                "es2017.arraybuffer",
                "es2017.date",
                "es2017.intl",
                "es2017.object",
                "es2017.sharedmemory",
                "es2017.string",
                "es2017.typedarrays",
                "es2018.asynciterable",
                "es2018.asyncgenerator",
                "es2018.promise",
                "es2018.regexp",
                "es2018.intl",
            ],
            Self::ES2019 => &[
                "es5",
                "es2015.core",
                "es2015.collection",
                "es2015.iterable",
                "es2015.generator",
                "es2015.promise",
                "es2015.proxy",
                "es2015.reflect",
                "es2015.symbol",
                "es2015.symbol.wellknown",
                "es2016.array.include",
                "es2016.intl",
                "es2017.arraybuffer",
                "es2017.date",
                "es2017.intl",
                "es2017.object",
                "es2017.sharedmemory",
                "es2017.string",
                "es2017.typedarrays",
                "es2018.asynciterable",
                "es2018.asyncgenerator",
                "es2018.promise",
                "es2018.regexp",
                "es2018.intl",
                "es2019.array",
                "es2019.object",
                "es2019.string",
                "es2019.symbol",
                "es2019.intl",
            ],
            Self::ES2020 => &[
                "es5",
                "es2015.core",
                "es2015.collection",
                "es2015.iterable",
                "es2015.generator",
                "es2015.promise",
                "es2015.proxy",
                "es2015.reflect",
                "es2015.symbol",
                "es2015.symbol.wellknown",
                "es2016.array.include",
                "es2016.intl",
                "es2017.arraybuffer",
                "es2017.date",
                "es2017.intl",
                "es2017.object",
                "es2017.sharedmemory",
                "es2017.string",
                "es2017.typedarrays",
                "es2018.asynciterable",
                "es2018.asyncgenerator",
                "es2018.promise",
                "es2018.regexp",
                "es2018.intl",
                "es2019.array",
                "es2019.object",
                "es2019.string",
                "es2019.symbol",
                "es2019.intl",
                "es2020.bigint",
                "es2020.date",
                "es2020.number",
                "es2020.promise",
                "es2020.sharedmemory",
                "es2020.string",
                "es2020.symbol.wellknown",
                "es2020.intl",
            ],
            Self::ES2021 => &[
                "es5",
                "es2015.core",
                "es2015.collection",
                "es2015.iterable",
                "es2015.generator",
                "es2015.promise",
                "es2015.proxy",
                "es2015.reflect",
                "es2015.symbol",
                "es2015.symbol.wellknown",
                "es2016.array.include",
                "es2016.intl",
                "es2017.arraybuffer",
                "es2017.date",
                "es2017.intl",
                "es2017.object",
                "es2017.sharedmemory",
                "es2017.string",
                "es2017.typedarrays",
                "es2018.asynciterable",
                "es2018.asyncgenerator",
                "es2018.promise",
                "es2018.regexp",
                "es2018.intl",
                "es2019.array",
                "es2019.object",
                "es2019.string",
                "es2019.symbol",
                "es2019.intl",
                "es2020.bigint",
                "es2020.date",
                "es2020.number",
                "es2020.promise",
                "es2020.sharedmemory",
                "es2020.string",
                "es2020.symbol.wellknown",
                "es2020.intl",
                "es2021.promise",
                "es2021.string",
                "es2021.weakref",
                "es2021.intl",
            ],
            Self::ES2022 => &[
                "es5",
                "es2015.core",
                "es2015.collection",
                "es2015.iterable",
                "es2015.generator",
                "es2015.promise",
                "es2015.proxy",
                "es2015.reflect",
                "es2015.symbol",
                "es2015.symbol.wellknown",
                "es2016.array.include",
                "es2016.intl",
                "es2017.arraybuffer",
                "es2017.date",
                "es2017.intl",
                "es2017.object",
                "es2017.sharedmemory",
                "es2017.string",
                "es2017.typedarrays",
                "es2018.asynciterable",
                "es2018.asyncgenerator",
                "es2018.promise",
                "es2018.regexp",
                "es2018.intl",
                "es2019.array",
                "es2019.object",
                "es2019.string",
                "es2019.symbol",
                "es2019.intl",
                "es2020.bigint",
                "es2020.date",
                "es2020.number",
                "es2020.promise",
                "es2020.sharedmemory",
                "es2020.string",
                "es2020.symbol.wellknown",
                "es2020.intl",
                "es2021.promise",
                "es2021.string",
                "es2021.weakref",
                "es2021.intl",
                "es2022.array",
                "es2022.error",
                "es2022.intl",
                "es2022.object",
                "es2022.regexp",
                "es2022.string",
            ],
            Self::ES2023 => &[
                "es5",
                "es2015.core",
                "es2015.collection",
                "es2015.iterable",
                "es2015.generator",
                "es2015.promise",
                "es2015.proxy",
                "es2015.reflect",
                "es2015.symbol",
                "es2015.symbol.wellknown",
                "es2016.array.include",
                "es2016.intl",
                "es2017.arraybuffer",
                "es2017.date",
                "es2017.intl",
                "es2017.object",
                "es2017.sharedmemory",
                "es2017.string",
                "es2017.typedarrays",
                "es2018.asynciterable",
                "es2018.asyncgenerator",
                "es2018.promise",
                "es2018.regexp",
                "es2018.intl",
                "es2019.array",
                "es2019.object",
                "es2019.string",
                "es2019.symbol",
                "es2019.intl",
                "es2020.bigint",
                "es2020.date",
                "es2020.number",
                "es2020.promise",
                "es2020.sharedmemory",
                "es2020.string",
                "es2020.symbol.wellknown",
                "es2020.intl",
                "es2021.promise",
                "es2021.string",
                "es2021.weakref",
                "es2021.intl",
                "es2022.array",
                "es2022.error",
                "es2022.intl",
                "es2022.object",
                "es2022.regexp",
                "es2022.string",
                "es2023.array",
                "es2023.collection",
                "es2023.intl",
            ],
            // ES2024+ and ESNext fall back to ES2023
            _ => Self::ES2023.default_libs(),
        }
    }
}

/// Project-level compiler options that affect validation and pipeline behavior.
///
/// This is distinct from `CheckerOptions` (which controls type-checking
/// behavior like strict mode). `CompilerOptions` holds settings such as
/// `target` and (in the future) `module`, `moduleResolution`, etc. that
/// determine which lib files are loaded, how modules are resolved, and
/// whether deprecated-option diagnostics are emitted.
#[derive(Debug, Clone, Default)]
pub struct CompilerOptions {
    pub target: Option<ScriptTarget>,
}

/// Validate compiler options, returning any diagnostics.
///
/// This checks for deprecated or removed option values and emits the
/// appropriate tsc-compatible error codes (e.g. TS5107 for deprecated
/// enum-valued options like `target=ES5`).
pub fn validate_compiler_options(options: &CompilerOptions) -> Vec<OxcDiagnostic> {
    let mut diagnostics = Vec::new();

    if let Some(target) = options.target {
        // TS5107: deprecated enum-valued compiler options.
        // tsc deprecation schedule: ES5 deprecated in 5.5, removed in 7.0,
        // silenced by ignoreDeprecations: "6.0".
        if target == ScriptTarget::ES5 {
            diagnostics.push(
                OxcDiagnostic::error(format!(
                    "Option 'target={}' is deprecated and will stop functioning in TypeScript 7.0. \
                     Specify compilerOption '\"ignoreDeprecations\": \"6.0\"' to silence this error.",
                    target.as_str()
                ))
                .with_error_code("ts", "5107"),
            );
        }
    }

    diagnostics
}
