name: autofix.ci # For security reasons, the workflow in which the autofix.ci action is used must be named "autofix.ci".

permissions: {}

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore:
      - "**/graphite-base/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: oxc-project/setup-node@4c26e7cb3605b6bdef5450dacd02c434b10fd8ba # v1.2.0

      - uses: oxc-project/setup-rust@23f38cfb0c04af97a055f76acee94d5be71c7c82 # v1.0.16
        with:
          restore-cache: true
          cache-key: warm
          tools: just,cargo-shear@1.11.2
          components: rustfmt

      - name: cargo-shear
        id: shear
        shell: bash
        run: |
          if ! cargo shear --fix; then
            echo "shear=true" >> $GITHUB_OUTPUT
          fi

      - name: Check and update lock file
        run: cargo check --all-features --all-targets
        if: ${{ steps.shear.outputs.shear == 'true' }}

      - run: just fmt

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
        with:
          fail-fast: false
