# Run cargo-llvm-cov and upload to codecov.io

name: Code Coverage

permissions: {}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - ".github/workflows/codecov.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  coverage:
    if: github.repository == 'oxc-project/oxc'
    name: Code Coverage
    runs-on: namespace-profile-linux-x64-default
    steps:
      - name: Checkout
        uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - name: Clone submodules
        uses: ./.github/actions/clone-submodules

      - uses: namespacelabs/nscloud-cache-action@a90bb5d4b27522ce881c6e98eebd7d7e6d1653f9 # v1.4.2
        with:
          path: /home/runner/.rustup
          cache: rust

      - uses: oxc-project/setup-node@4c26e7cb3605b6bdef5450dacd02c434b10fd8ba # v1.2.0

      - run: rustup component add llvm-tools-preview
      - uses: taiki-e/install-action@0abfcd587b70a713fdaa7fb502c885e2112acb15 # v2.75.7
        with:
          tool: cargo-llvm-cov

      - name: Run
        env:
          # Increase stack size to 10MB, avoid `oxc_formatter` from stack overflowing when printing long assignment expressions.
          RUST_MIN_STACK: 104857600
        run: cargo codecov --lcov --output-path lcov.info

      - name: Upload Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          if-no-files-found: error
          name: codecov
          path: lcov.info

  # codecov often fails, use another workflow for retry
  upload-codecov:
    name: Upload coverage file
    runs-on: ubuntu-slim
    needs: coverage
    # Check if the event is not triggered by a fork by checking whether CODECOV_TOKEN is set
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout
        if: env.CODECOV_TOKEN
        uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - name: Download coverage file
        if: env.CODECOV_TOKEN
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: codecov

      - name: Upload to codecov.io
        if: env.CODECOV_TOKEN
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: lcov.info
