name: Cargo Deny

permissions: {}

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "Cargo.lock"
      - "deny.toml"
      - ".github/workflows/deny.yml"
  push:
    branches:
      - main
    paths:
      - "Cargo.lock"
      - "deny.toml"
      - ".github/workflows/deny.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: oxc-project/setup-rust@23f38cfb0c04af97a055f76acee94d5be71c7c82 # v1.0.16
        with:
          restore-cache: false
          tools: cargo-deny

      - run: cargo deny check
