name: Update implementation status of all linter plugins

permissions: {}

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/lint_rules.yml"
      - "crates/oxc_linter/src/rules.rs"
      - "crates/oxc_linter/src/utils/mod.rs" # here are the remaps for some plugins
      - "tasks/lint_rules/**"

jobs:
  lint_rules:
    if: github.repository == 'oxc-project/oxc'
    runs-on: ubuntu-slim
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout Branch
        uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1

      - uses: oxc-project/setup-node@b8d296d30eafd1ae2968fab67aead472a1dbf6d4 # v1.0.7

      - name: Install latest plugins
        working-directory: tasks/lint_rules
        run: npm install

      - name: Run task
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node ./tasks/lint_rules --update
