name: Check PR

permissions: {}

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr:
    if: github.repository == 'oxc-project/oxc'
    name: Check PR Title
    permissions:
      pull-requests: read
    runs-on: ubuntu-slim
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: true
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            release
            revert
            style
            test
