name: Release Crates

permissions: {}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - crates/oxc/Cargo.toml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    if: github.repository == 'oxc-project/oxc'
    name: Release crates
    runs-on: ubuntu-latest
    environment: crates
    permissions:
      contents: write # For git tag push
      id-token: write # Required for OIDC token exchange
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0 # for changelog
          persist-credentials: true

      - uses: oxc-project/setup-rust@3d6fb132fbe7cdcb66bf8ec193911c2945369d12 # v1.0.17
        with:
          cache-key: warm
          tools: cargo-release-oxc

      - run: cargo ck

      - name: Generate changelog
        run: |
          mkdir -p target
          cargo release-oxc changelog --release crates

      - uses: rust-lang/crates-io-auth-action@bbd81622f20ce9e2dd9622e3218b975523e45bbe # v1.0.4
        id: auth

      - name: Run
        id: run
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          cargo release-oxc publish --release crates
          echo "TAG=$(cat ./target/CRATES_VERSION)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
          GIT_TAG: ${{ steps.run.outputs.TAG }}
          GIT_TARGET: ${{ github.sha }}
          TITLE: "oxc ${{ steps.run.outputs.TAG }}"
        run: gh release create ${GIT_TAG} --latest=false --title "${TITLE}" --notes-file ./target/CRATES_CHANGELOG --target ${GIT_TARGET}
