name: Release Crates

permissions: {}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - crates/oxc/Cargo.toml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    if: github.repository == 'oxc-project/oxc'
    name: Release crates
    runs-on: ubuntu-latest
    permissions:
      contents: write # For git tag push
      id-token: write # Required for OIDC token exchange
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.OXC_BOT_PAT }}
          fetch-depth: 0 # for changelog
          persist-credentials: true

      - uses: oxc-project/setup-rust@23f38cfb0c04af97a055f76acee94d5be71c7c82 # v1.0.16
        with:
          cache-key: warm
          tools: cargo-release-oxc

      - run: cargo ck

      - name: Generate changelog
        run: |
          mkdir -p target
          cargo release-oxc changelog --release crates

      - uses: rust-lang/crates-io-auth-action@b7e9a28eded4986ec6b1fa40eeee8f8f165559ec # v1.0.3
        id: auth

      - name: Run
        id: run
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          cargo release-oxc publish --release crates
          echo "TAG=$(cat ./target/CRATES_VERSION)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
          GIT_TAG: ${{ steps.run.outputs.TAG }}
          GIT_TARGET: ${{ github.sha }}
          TITLE: "oxc ${{ steps.run.outputs.TAG }}"
        run: gh release create ${GIT_TAG} --latest=false --title "${TITLE}" --notes-file ./target/CRATES_CHANGELOG --target ${GIT_TARGET}
